- src/Dropdown/theme.scss
- src/Header/header.theme.scss
added styles using gov styles directly
> Head dropdown styles

- backend/session.js
- src/App.js
- src/App.test.js
- src/ResultsHouseblock/ResultsHouseblockContainer.js
- src/Search/SearchContainer.js
added session timeout (cookie expiry) and global error handler
> Session timeout

- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/HouseblockSpecification.groovy
- src/App.scss
- src/ResultsHouseblock/ResultsHouseblock.js
- src/ResultsHouseblock/ResultsHouseblock.test.js
- src/ResultsHouseblock/ResultsHouseblockContainer.js
- src/ResultsHouseblock/index.scss
- Fix table background colour toggle
- Remove agency prefix
- Fix padding issues
> NN 921 whereabouts house block print report tweaks

- src/ResultsHouseblock/ResultsHouseblock.js
- src/ResultsHouseblock/ResultsHouseblock.test.js
- src/lists.scss
- Remove sorted column colour on print
- Add period to the top of the page next to date on print
> NN-921 Fix whereabouts print report background colours

- src/Dropdown/theme.scss
- src/index.scss
> NN-955 Make react applications work with IE11

- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/HouseblockSpecification.groovy
- src/Search/SearchContainer.js
- Remove code that sets the current location to the first one in the list
> NN-1001-housing-lov-should-default-to-select

- webpack.config.js
- Can't recreate the actual error but hot module reloading was running in production and was potentially causing errors when the frontend requested updates.
> NN-1003-blank-screen-console-errors-returned

- package.json
- yarn.lock
Use 3.1 for now - v4.0.0 requires a css stylesheet in <head>
> NN-998 spinner icon not spinning

- src/Footer/footer.scss
- src/Footer/index.js
> NN-961 Logged in T's & C's & feedback email links differ to NN & KW

- backend/controllers/houseblockList.js
- backend/sessionManagementRoutes.js
- backend/tests/hmppsCookie.test.js
- backend/tests/houseblockList.test.js
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/mockapis/mockResponses/HouseblockResponse.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/HouseblockSpecification.groovy
- src/App.test.js
- src/ModalProvider/PaymentReasonModal/paymentReasonContainer.test.js
- src/ModalProvider/PaymentReasonModal/paymentReasonModal.test.js
- src/ModalProvider/index.js
- src/ModalProvider/modalProvider.test.js
- src/ResultsActivity/ResultsActivity.js
- src/ResultsActivity/ResultsActivity.test.js
- src/ResultsHouseblock/ResultsHouseblock.js
- src/ResultsHouseblock/ResultsHouseblock.test.js
Id look at the commits separately as I cleaned up a lot of test warnings
> Nn 1026 only one main activity

- backend/controllers/houseblockList.js
- src/Search/Search.js
Also a bit of a refactor of NN-1026
> Nn 1029 change search field screen headings

- src/Search/Search.js
Avoid any concurrency problems by disabling 'Continue' as well as the dropdown
> NN-1063 Activity LOV Filter (disable continue button)

- src/App.scss
> NN-1109 Printed Whereabouts lists. Make tr a.link:visited black for @media print.

- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/HouseblockSpecification.groovy
- src/App.js
- src/ResultsHouseblock/ResultsHouseblock.js
- src/ResultsHouseblock/ResultsHouseblock.test.js
- src/ResultsHouseblock/ResultsHouseblockContainer.js
Also fixed a bug in code which populates the sub-locations select options on Residential Locations search results page.
> NN-1138 New default sorting rules for Residential Location search results.

- backend/controllers/activityList.js
- backend/controllers/houseblockList.js
- backend/shared/getExternalEventsForOffenders.js
- backend/tests/activityList.test.js
- backend/tests/getExternalEventsForOffenders.test.js
- backend/tests/houseblockList.test.js
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/mockapis/Elite2Api.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/mockapis/mockResponses/HouseblockResponse.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/ActivitySpecification.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/HouseblockSpecification.groovy
- src/OtherActivityListView/index.js
- src/ResultsActivity/ResultsActivity.test.js
**Expose court event status descriptions**
> NN-1144 Court event status descriptions

- src/App.scss
- src/ResultsActivity/ResultsActivity.js
- src/ResultsActivity/ResultsActivity.test.js
- src/ResultsHouseblock/ResultsHouseblock.js
- src/ResultsHouseblock/ResultsHouseblock.test.js
- src/lists.scss
- Adjusted print font sizes and padding for the whereabouts results list/table
- Removed titles and dates from the top of the page
> NN-1160 Updated whereabouts print style changes

- src/index.js
See https://github.com/zalmoxisus/redux-devtools-extension#usage
> Add support for redux devtools

- src/index.js
Reverts ministryofjustice/prisonstaffhub#136
> Revert "Add support for redux devtools"

- backend/controllers/establishmentRollCount.js
- backend/tests/establishmentRollCount.test.js
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/EstablishmentRollBlockSpecification.groovy
Reverts ministryofjustice/prisonstaffhub#142
Some confusion over whether this change required or not.  Confirmed with Dom and John that we don't.
> Revert "NN-1169 Correct calculation for unassigned movements figure"

- src/Error/error.test.js
- src/Footer/footer.test.js
- src/ModalProvider/PaymentReasonModal/paymentReasonContainer.test.js
- src/ModalProvider/PaymentReasonModal/paymentReasonModal.test.js
- src/ModalProvider/modalProvider.test.js
- src/ResultsActivity/ResultsActivity.test.js
- src/ResultsHouseblock/ResultsHouseblock.test.js
- src/Search/Search.test.js
Individual Enzyme adapters are no longer required since the addition of the setupTests.js
> Remove unnecessary Enzyme adapters

- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/mockapis/Elite2Api.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/mockapis/mockResponses/ActivityResponse.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/mockapis/mockResponses/HouseblockResponse.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/ActivitySpecification.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/HouseblockSpecification.groovy
- src/App.scss
- src/OtherActivityListView/index.js
- src/ResultsActivity/ResultsActivity.js
- src/ResultsActivity/ResultsActivity.test.js
- src/ResultsHouseblock/ResultsHouseblock.js
- src/ResultsHouseblock/ResultsHouseblock.test.js
- src/utils.js
- yarn.lock
**Changes apply to both lists**
- Display the location for appointments via the other activities 
- Reposition the time to the start of the event description for main and other activities
- Include the start time for appointments via the other activities
- Fix margin on sort order drop-down
> Nn 1420 display appointment location and change date format

- package.json
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/EstablishmentRollPage.groovy
- src/App.js
- src/EstablishmentRoll/EstablishmentRoll.js
- src/EstablishmentRoll/EstablishmentRoll.test.js
- src/Page/Page.js
- src/Page/Page.styles.js
- src/Page/Page.test.js
- yarn.lock
Added <Page /> component that was created in omic-ui to help us standardise and create new pages easily. So it handles the following in one place:
- Breadcrumbs/back button
- Loading state
- Error state
- Page titles
> NN-1398 establishment roll back

- backend/controllers/establishmentRollCount.js
- backend/tests/establishmentRollCount.test.js
- backend/utils.js
- backend/utils.test.js
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/mockapis/mockResponses/EstablishmentRollResponses.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/EstablishmentRollBlockSpecification.groovy
- NN-1449 renamed Movements to Todays movements
- NN-1460 Renamed Unassigned to In reception on ER page
- NN-1399 Capitalize Houseblock descriptions
> NN-1449-1460-1399 Establishment roll updates

- backend/api/elite2Api.js
- backend/api/oauthApi.js
- backend/api/oauthClientId.js
- backend/config.js
- backend/controllers/movementsService.js
Add ability to use oauth clientId
Also example code in movements service
> NN-1486 Add an alert API endpoint to Elite2

- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/mockapis/Elite2Api.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/mockapis/OauthApi.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/OutTodayPage.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/MovementssSpecification.groovy
- src/FullFlags/FullFlags.js
- src/MovementsOut/MovementsOut.js
- src/MovementsOut/MovementsOut.test.js
- src/MovementsOut/__snapshots__/MovementsOut.test.js.snap
- Added integration tests
- Added snapshot unit test
- Fixed propTypes
> NN-1512 Movements out tests

- webpack.config.js
> Intermediate fix for the issue around requests for bundle.js.map

- backend/api/elite2Api.js
- backend/controllers/controller.js
- backend/controllers/movementsService.js
- backend/index.js
- backend/tests/movementsService.test.js
- backend/utils.js
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/mockapis/Elite2Api.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/InReception.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/MovementsSpecification.groovy
- src/App.js
- src/EstablishmentRoll/EstablishmentRollBlock.js
- src/InReception/InReception.js
- src/InReception/InReception.test.js
- src/InReception/InReceptionContainer.js
- src/InReception/__snapshots__/InReception.test.js.snap
- src/MovementsIn/MovementsIn.test.js
- src/MovementsIn/MovementsInContainer.js
- src/MovementsIn/__snapshots__/MovementsIn.test.js.snap
- src/MovementsOut/MovementsOut.js
- src/MovementsOut/MovementsOut.test.js
- src/MovementsOut/MovementsOutContainer.js
- src/routePaths.js
- src/tablesorting/SortableDataSource.js
- src/tablesorting/SortableDataSource.test.js
- src/tablesorting/comparatorComposition.js
- Integrate with the in-reception endpoint
- Create new in reception results page
- Move sorting logic into a new sortable component
> NN-1443 In Reception

- src/MovementsIn/MovementsIn.js
- src/MovementsIn/MovementsIn.test.js
- src/MovementsIn/MovementsInContainer.js
- src/MovementsIn/__snapshots__/MovementsIn.test.js.snap
- src/MovementsOut/MovementsOut.js
- src/MovementsOut/__snapshots__/MovementsOut.test.js.snap
- src/tablesorting/SortableDataSource.js
- src/tablesorting/SortableDataSource.test.js
- Fix key on offender results causing sorting to be an issue with new data
- Remove clickable link from offenders when their not in the current case load
> NN-1557 in today result page fixes

- html-template/index.html
- src/App.js
- src/BulkAppointments/BulkAppointmentsContainer.js
- src/Components/Content/Content.js
- src/Components/Page/Page.js
- src/FooterContainer/FooterContainer.js
- Open footer links in new tab
- Prevent undefined momentarily appearing in document title
- Change black bar app title to Digital Prison Services
> NN-1655 footer pages

- src/AppointmentDetails/AppointmentDetails.js
- src/AppointmentDetails/__snapshots__/AppointmentDetails.test.js.snap
- src/BulkAppointments/AddPrisoners/AddPrisonerValidation.js
- src/BulkAppointments/AddPrisoners/AddPrisonersContainer.js
- src/BulkAppointments/AddPrisoners/AddPrisonersValidation.test.js
- src/BulkAppointments/AddPrisoners/__snapshots__/AddPrisonerContainer.test.js.snap
- Renamed validation
- Added end time to appointment details
- Wording changes
- Fix format on start times
> NN-1704 bulk appointments validation bug

- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/AddBulkAppointmentsPage.groovy
- src/BulkAppointments/AddPrisoners/AddPrisonerContainer.test.js
- src/BulkAppointments/AddPrisoners/AddPrisonersContainer.js
- src/BulkAppointments/AddPrisoners/__snapshots__/AddPrisonerContainer.test.js.snap
- src/BulkAppointments/AppointmentDetailsForm/AppointmentDetailsFormValidation.js
- src/BulkAppointments/AppointmentDetailsForm/AppointmentDetailsFormValidation.test.js
- Tweak wording on the created screen
- Fix date validation
> NN-859 recurring tweaks

- html-template/index.html
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/mockapis/OauthApi.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/LoginPage.groovy
- routes/index.js
- src/Components/Page/Page.js
- src/Components/Page/Page.test.js
- src/redux/reducers/index.js
- src/redux/reducers/reducers.test.js
- views/autherror.ejs
Reverts ministryofjustice/prisonstaffhub#304
> Revert "NN-1724 Revert name change"

- html-template/index.html
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/mockapis/OauthApi.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/LoginPage.groovy
- routes/index.js
- src/Components/Page/Page.js
- src/Components/Page/Page.test.js
- src/redux/reducers/index.js
- src/redux/reducers/reducers.test.js
- views/autherror.ejs
Reverts ministryofjustice/prisonstaffhub#314
> Revert "Revert "NN-1724 Revert name change""

- package.json
- src/GlobalSearch/GlobalSearch.scss
- src/GlobalSearch/GlobalSearchContainer.js
- src/GlobalSearch/GlobalSearchContainer.test.js
- src/GlobalSearch/GlobalSearchForm.js
- src/GlobalSearch/GlobalSearchForm.styles.js
- src/GlobalSearch/GlobalSearchResultList.js
- Global search form submits on enter keypress
- Replaced selects and button with those from govuk-react 
- Search form is now presentable on smaller screens/mobile
> NN-1504 Accessible global search form

- html-template/index.html
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/mockapis/OauthApi.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/LoginPage.groovy
- routes/index.js
- src/Components/Page/Page.js
- src/Components/Page/Page.test.js
- src/redux/reducers/index.js
- src/redux/reducers/reducers.test.js
- views/autherror.ejs
Reverts ministryofjustice/prisonstaffhub#315
> Revert "Revert "Revert "NN-1724 Revert name change"""

- backend/azure-appinsights.js
Reverts ministryofjustice/prisonstaffhub#336
Not needed as these values are the default.
> Revert "improve-app-insight-logging"

- backend/config.js
- backend/controllers/getConfig.js
- package.json
- src/Components/PayOffender/PayOffender.js
- src/Components/PayOffender/PayOffender.test.js
- src/Components/PayOffender/index.js
- src/DatePickers/FormDatePicker.test.js
- src/ResultsActivity/ResultsActivity.js
- src/ResultsActivity/ResultsActivity.test.js
- src/ResultsActivity/ResultsActivityContainer.js
- src/redux/reducers/index.js
- src/redux/reducers/reducers.test.js
- yarn.lock
- Add UPDATE_ATTENDANCE_ENABLED env feature toggle
- Add <PayOffender /> component
> NN-1559 Add <PayOffender /> component

- src/ResultsActivity/ResultsActivity.js
- src/ResultsActivity/elements/PayOptions/PayOptions.js
- src/ResultsActivity/elements/PayOptions/PayOptions.test.js
Enzyme doesn't support hooks properly yet so opted to use react-test-renderer.
> NN-1560 Added some tests around pay options

- src/IepDetails/IepHistory.js
- src/IepDetails/IepHistory.test.js
- src/IepDetails/IepHistoryForm.js
- src/IepDetails/__snapshots__/IepHistory.test.js.snap
- src/IepDetails/__snapshots__/IepHistoryForm.test.js.snap
Also fixed incorrect PropType warning for `days`
> NN-1939 UI tweaks for IEP history

- backend/controllers/attendance.js
- backend/tests/attendance.test.js
- src/Components/PayOtherForm/PayOtherForm.js
- src/Components/PayOtherForm/PayOtherForm.test.js
> NN-1948 first part, handle absent reasons

- package.json
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/AdjudicationDetailPage.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/AdjudicationHistoryPage.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/AdjudicationsSpecification.groovy
- src/Adjudications/AdjudicationHistory/AdjudicationHistoryTable.js
- src/Adjudications/AdjudicationHistory/AdjudicationHistoryTable.test.js
- src/Adjudications/AdjudicationHistory/__snapshots__/AdjudicationHistoryTable.test.js.snap
- src/OffenderPage/OffenderPage.js
- src/OffenderPage/OffenderPage.test.js
- src/redux/reducers/offenderDetails.js
This is hidden behind a feature flag
> NN-1677 Adding adjudication details link. 

- src/Components/ResultsTable/elements/TotalResults/TotalResults.js
- src/Components/ResultsTable/elements/TotalResults/TotalResults.test.js
- src/Components/ResultsTable/elements/TotalResults/__snapshots__/TotalResults.test.js.snap
- src/Components/ResultsTable/elements/TotalResults/index.js
- src/ResultsActivity/ResultsActivity.js
- src/ResultsActivity/ResultsActivity.test.js
- src/ResultsHouseblock/ResultsHouseblock.js
- src/ResultsHouseblock/ResultsHouseblock.test.js
- src/tablesorting/SortLov.js
Raised [NN-1986](https://dsdmoj.atlassian.net/browse/NN-1986) while doing this as both lists could be combined into one as they're effectively the same thing and we're having to duplicate work.
> NN-1761 Add total results number to activity and houseblock lists

- backend/config.js
- backend/controllers/activityList.js
- backend/controllers/getConfig.js
- backend/tests/activityList.test.js
- backend/tests/activityListWithDisabledFeatures.test.js
- src/App.js
- src/ResultsActivity/ResultsActivity.js
- src/ResultsActivity/ResultsActivityContainer.js
- src/redux/reducers/index.js
- src/redux/reducers/reducers.test.js
Enable update attendance/pay at prison level with comma separated list of prisons in an environment variable.
e.g. `UPDATE_ATTENDANCE_PRISONS=MDI,LEI`
> NN-1994 Enable update attendance/pay at prison level

- package.json
- yarn.lock
> NN-2026 Remove unused fs security holding package

- backend/controllers/attendance.js
- backend/tests/attendance.test.js
Updated attendance controller to add '- IEP' wording to absence reasons that trigger an IEP warning.
> NN-2037 Updated attendance controller to show IEP warnings

- backend/config.js
- backend/services/healthCheck.js
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/ActivitySpecification.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/HealthSpecification.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/HouseblockSpecification.groovy
Reverts ministryofjustice/prisonstaffhub#432
> Revert "disable pay"

- package.json
- src/IEPCreated/IEPCreated.js
- src/IEPCreated/IEPCreated.test.js
- yarn.lock
Reverts ministryofjustice/prisonstaffhub#437
> Revert "NN-1909 Hide print IEP slip button on mobile devices"

- package.json
- src/IEPCreated/IEPCreated.js
- src/IEPCreated/IEPCreated.test.js
- yarn.lock
Reverts ministryofjustice/prisonstaffhub#439
> Revert "Revert "NN-1909 Hide print IEP slip button on mobile devices""

- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/HouseblockSpecification.groovy
- src/ResultsActivity/elements/PayOptions/PayOptions.js
- src/ResultsHouseblock/ResultsHouseblock.js
There is a bit of a complex decision matrix for this, but in a nutshell:
Paid and locked - Paid
Paid and not locked - Received
Other and locked - Absence reason plain text
Other and not locked - Absence reason as link
Not recorded within 7 days - radio button to update
Not recorded after 7 days - Not Recorded
> NN-2059: Update attendance information on houseblock lists

- src/GlobalSearch/GlobalSearchContainer.js
- src/GlobalSearch/GlobalSearchContainer.test.js
- src/GlobalSearch/GlobalSearchResultList.js
- src/GlobalSearch/__snapshots__/GlobalSearchResultList.test.js.snap
This reverts commit ef18780077daf7969b7c1a950446590e47d0b5a9.
> Revert "DT-98: Link to offenders for global search users"

- backend/controllers/iepDetails.js
- backend/controllers/iepDetails.test.js
Reverts ministryofjustice/prisonstaffhub#459
> Revert "NN-2103: Remove Entry from possible options for Change IEP"

- src/ResultsActivity/ResultsActivity.js
- src/ResultsActivity/ResultsActivity.test.js
- src/ResultsActivity/elements/PayOptions/PayOptions.js
Update of the attend all request to cater to multiple activities for one prisoner.
Search by eventId rather than bookingId
> NN-2111 updated offender search to prevent dupes and associated tests

- src/MissingPrisoners/MissingPrisoners.js
- src/MissingPrisoners/MissingPrisonersContainer.js
- src/MissingPrisoners/MissingPrisonersSearch.js
- src/MissingPrisoners/MissingPrisonersSearch.style.js
- Add reload page link to missing prisoner
- Also moved Search styles into their own file as they were getting quite big
> NN-1805 Add reload page link to missing prisoners

- src/GlobalSearch/GlobalSearchContainer.js
- src/GlobalSearch/GlobalSearchContainer.test.js
- src/GlobalSearch/GlobalSearchResultList.js
- src/GlobalSearch/__snapshots__/GlobalSearchResultList.test.js.snap
Reverts ministryofjustice/prisonstaffhub#458
> Revert "Revert "DT-98: Link to offenders for global search users""

- src/MissingPrisoners/MissingPrisonersSearch.js
- src/MissingPrisoners/MissingPrisonersSearch.style.js
- Updated visible elements to print
- removed controls from printable view
- Added date to printable view
> NN-2122 updated styled elements and added classes to handle visibility

- src/Search/Search.js
- src/Search/Search.test.js
- src/Search/__snapshots__/Search.test.js.snap
For https://dsdmoj.atlassian.net/browse/NN-2125
> Nn 2125 missing prisoners button

- src/DatePickers/WhereaboutsDatePicker.js
- src/DatePickers/WhereaboutsDatePicker.test.js
- src/ResultsActivity/ResultsActivity.js
- src/ResultsHouseblock/ResultsHouseblock.js
- src/Search/Search.test.js
- src/Search/__snapshots__/Search.test.js.snap
- src/utils.js
- src/utils.test.js
- Allow datepicker to select next 7 days by default
- Only display Print button on Activity and Housing lists for next 2 working days
> NN-2119 Datepicker and print button changes

- src/Search/Search.js
- src/Search/Search.test.js
- src/utils.js
Hide missing prisoners button for future dates and periods but allow any period to be selected on previous days.
> NN-2119 Hide missing prisoners button for future dates and periods

- backend/api/elite2Api.js
- backend/controllers/controller.js
- backend/controllers/offenderService.js
- backend/controllers/reference-codes-service.js
- backend/index.js
- backend/tests/controllers.test.js
- backend/tests/reference-codes-service.test.js
- src/App.js
- src/BulkAppointments/AppointmentDetailsForm/AppointmentDetailsForm.js
- src/CreateAlert/CreateAlertContainer.js
- src/CreateAlert/CreateAlertContainer.test.js
- src/CreateAlert/CreateAlertForm.js
- src/CreateAlert/CreateAlertForm.test.js
- src/CreateAlert/CreateAlertValidation.test.js
- src/CreateAlert/__snapshots__/CreateAlertContainer.test.js.snap
- src/CreateAlert/__snapshots__/CreateAlertForm.test.js.snap
- src/OffenderPage/OffenderPage.js
- src/OffenderPage/__snapshots__/OffenderPage.test.js.snap
- src/routePaths.js
- src/routes.js
Reverts ministryofjustice/prisonstaffhub#487
> Revert "Revert "NN-1857 create alert""

- .circleci/config.yml
- bin/build-css
- package.json
- Persisted designated css folder structure to the workspace
- amended ordering of css compile and build
> Nn 2156 circle ci css compile fix

- .circleci/config.yml
- bin/build-css
Removed rel path update from bin file and removed folder reference from circle config
> NN-2156 revert yml update and relative path change

- backend/controllers/attendanceStatistics.js
- backend/tests/attendanceStatistics.test.js
- static/js/main.js
- views/components/datePicker.njk
- views/error.njk
Readonly date input as agreed with Andy H/Eddie/Jamie
Updated format to match GDS.
More appropriate error handling to match GDS, improved breadcrumb and link back to stats page from error page.
> NN-2159 date entry update and error handling

- backend/controllers/attendanceStatistics.js
- backend/index.js
- backend/tests/attendanceStatistics.test.js
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/ActivityPage.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/HouseblockPage.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/SearchPage.groovy
- src/App.js
- src/Dashboard/index.js
- src/ResultsActivity/ResultsActivityContainer.js
- src/ResultsHouseblock/ResultsHouseblockContainer.js
- src/Search/Search.js
- src/Search/SearchContainer.js
- src/Search/__snapshots__/Search.test.js.snap
- src/routePaths.js
- src/routes.js
- views/attendanceStatistics.njk
- views/error.njk
Changed search-prisoner-whereabouts to manage-prisoner-whereabouts
> NN-2162 Updated whereabouts breadcrumbs and paths

- backend/utils.js
- backend/utils.test.js
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/ActivitySpecification.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/HouseblockSpecification.groovy
- src/AlertFlags/AlertFlags.js
- src/AlertFlags/AlertFlags.scss
- src/AlertFlags/AlertFlags.test.js
- src/AlertFlags/index.js
- src/ResultsActivity/ResultsActivity.js
- src/ResultsActivity/ResultsActivity.test.js
- src/ResultsHouseblock/ResultsHouseblock.js
- src/ResultsHouseblock/ResultsHouseblock.test.js
- Added PEEP alert flag to lists
- Added missing tests
- Formatted spacing between flags
> NN-2129 Show PEEP flag on lists

- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/ActivityPage.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/HouseblockSpecification.groovy
- src/ResultsActivity/ResultsActivity.js
- src/ResultsActivity/ResultsActivity.test.js
- src/ResultsActivity/ResultsActivityContainer.js
- src/ResultsHouseblock/ResultsHouseblock.js
- src/ResultsHouseblock/ResultsHouseblock.test.js
- src/ResultsHouseblock/ResultsHouseblockContainer.js
- redacted print versions for houseblock and activity lists
- removed non required links from existing print version (as per NN-2140)
> Nn 1765 redacted prisoner list print version

- backend/controllers/offenderActivities.js
- backend/tests/offenderActivities.test.js
- src/ResultsActivity/ResultsActivity.js
- src/ResultsActivity/ResultsActivity.test.js
Also change _Attend all prisoners_ text to _All prisoners have attended_
> NN-2117 Fix missing prisoners after api contract change

- backend/controllers/attendanceStatistics.js
- backend/tests/attendanceStatistics.test.js
> NN-2190 Fix attendance dashboard to use new whereabouts attendance data structure

- backend/controllers/attendanceStatistics.js
- backend/controllers/bulkAppointmentsConfirm.js
- backend/controllers/downloadProbationDocument.js
- backend/index.js
- backend/tests/attendanceStatistics.test.js
- backend/tests/bulkAppointmentsConfirm.test.js
- backend/tests/downloadProbationDocument.test.js
- views/confirmAppointments.njk
- views/error.njk
- views/partials/layout.njk
- First version of bulk appointments confirmation page
- Set title in error.njk rather than passing it as a title param every time it's used
- Added 'Digital Prison Service' suffix to <title> in layout.njk
> NN-2173 First version of bulk appointments confirmation page

- backend/controllers/bulkAppointmentsConfirm.js
- backend/tests/bulkAppointmentsConfirm.test.js
- views/components/timePicker/timePicker.njk
- views/confirmAppointments.njk
- Update bulk appointment to account for no start date/time and end date/time
- Added `aria-label` to timepicker in absence of `<label>`
- Added classes param to timepicker
> NN-2173 Update bulk appointment confirm page values

- backend/controllers/bulkAppointmentsUpload.js
- backend/controllers/bulkAppointmentsUploadController.js
- backend/csv-parser.js
- backend/index.js
- backend/tests/bulkOffenderUpload.test.js
- backend/tests/csv-parser.test.js
- views/addBulkAppointments.njk
- views/uploadOffenders.njk
- new controller structure
- updated error handling for no file
- added tests for empty file and no file
- updated view to handle conditional data.
> Nn 2172 correct error messages for file upload

- backend/controllers/bulkAppointmentsConfirm.js
- backend/tests/bulkAppointmentsConfirm.test.js
Also removed unnecessary check for date on `isToday`, as there's always a date set by then.
> NN-2175 Updated test to account for start time in past

- backend/api/elite2Api.js
- backend/controllers/bulkAppointmentsClashes.js
- backend/controllers/bulkAppointmentsSlipsController.js
- backend/routes.js
- backend/tests/bulkAppointmentsClashes.test.js
- backend/tests/bulkAppointmentsSlipsController.test.js
- backend/utils.js
- sass/application.scss
- views/appointmentsAdded.njk
- views/components/movementSlip/movementSlip.njk
- views/components/movementSlip/movementSlip.scss
- views/movementSlipsPage.njk
> NN-2182 Printed movement authorisation slips

- .circleci/config.yml
Reverts ministryofjustice/prisonstaffhub#603
> Revert "build and build_docker in parallel"

- backend/sessionManagementRoutes.js
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/HouseblockPage.groovy
- prisonstaffhub-specs/src/test/resources/GebConfig.groovy
Reverts ministryofjustice/prisonstaffhub#605
> Revert "Apply Petes fix for integration tests"

- backend/api/whereaboutsApi.js
- backend/controllers/attendanceStatistics.js
- backend/routes.js
- backend/tests/attendanceStatistics.test.js
- backend/utils.js
- sass/application.scss
- sass/components/_sortable-table.scss
- src/tablesorting/SortableColumn.js
- static/js/sortable-table.js
- views/attendanceStatistics.njk
- views/attendanceStatisticsOffendersList.njk
This adds the ability to click on some of the numbers on the attendance statistics dashboard and be taken to a list of the offenders behind those numbers. Includes implementing table sorting in the non-react side of the site.
> Nn 2030 offender list attendance reasons

- backend/controllers/bulkAppointmentsUpload.js
- Updates to session were conditional on there being missing/prisoners in the list.  This isn't the way it should work as an empty list can be passed through.
> NN-2220 removed conditions which prevent session update

- src/EstablishmentRoll/EstablishmentRollContainer.js
- src/EstablishmentRoll/EstablishmentRollContainer.test.js
Conditionally show EstablishmentRollBlocks only when there is data
> NN-2261 Fix establishment roll intermittent white screen

- backend/controllers/bulkAppointmentsPrisonersNotFound.js
- backend/controllers/bulkAppointmentsPrisonersNotFoundController.js
- backend/controllers/bulkAppointmentsUpload.js
- backend/routes.js
- backend/tests/bulkAppointmentsUpload.test.js
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/BulkAppointmentsAddedPage.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/BulkAppointmentsConfirmPage.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/BulkAppointmentsPrisonersNotFoundPage.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/BulkAppointmentsUploadCSVPage.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/BulkAppointmentsSpecification.groovy
- prisonstaffhub-specs/src/test/resources/offenders-for-appointments-with-missing.csv
- views/confirmAppointments.njk
- views/prisonersNotFound.njk
Also re-added the integration tests which were deleted in error as part of NN-2238 😮
> NN-2216 Added prisoners not found page to BA journey

- package.json
- yarn.lock
Before: 9595 vulnerabilities reported by `yarn audit` , after: 0. And the site still runs!
> Nn 2307 fix security vulnerabilities

- backend/controllers/addAppointment.js
- backend/controllers/appointmentsService.js
- backend/controllers/bulkAppointmentsAddDetails.js
- backend/routes.js
- backend/shared/appointmentConstants.js
- backend/tests/addAppointment.test.js
- backend/tests/appointmentsService.test.js
- backend/tests/bulkAppointmentsAddDetails.test.js
- views/addAppointment.njk
- Handle add appointment form post
- Changed what is returned from appointment options in the appointment service
- Created shared appointments file which just has `repeatTypes` in there (plan is for this to also contain some shared validation between this and bulk appt)
Next to do: 
- Add form validation
- Clashing appointments
> NN-2325 Handle add appointment form post

- backend/api/elite2Api.js
- backend/controllers/activityList.js
- backend/tests/activityList.test.js
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/mockapis/Elite2Api.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/ActivitySpecification.groovy
- src/App.scss
- src/ResultsActivity/ResultsActivity.js
- src/ResultsActivity/ResultsActivity.test.js
> NN-2235 include suspended activity lists

- views/appointmentClashes.njk
> NN-2325 Add wording when there are no clashes to display

- backend/controllers/confirmAppointment.js
- backend/shared/appointmentConstants.js
- backend/tests/confirmAppointments.test.js
- src/BulkAppointments/RecurringAppointments.js
Use correct end date calculator.
> NN-2351 fix enddate bug

- views/components/scheduledEvents/scheduledEvents.njk
- views/components/scheduledEvents/scheduledEvents.scss
> NN-2291 Layout tweaks to event clashes boxes

- backend/api/elite2Api.js
- backend/controllers/prepostAppoinments.js
- backend/controllers/prepostAppointmentsController.js
- backend/tests/prepostAppointments.test.js
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/mockapis/Elite2Api.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/AddAppointmentSpecification.groovy
- static/js/main.js
- views/prepostAppointments.njk
> Nn 2338 pre post clashes

- backend/controllers/addAppointment.js
- backend/controllers/endDateController.js
- backend/routes.js
- backend/tests/addAppointment.test.js
- src/BulkAppointments/RecurringAppointments.js
- static/js/main.js
- views/addAppointment/addAppointment.njk
Also fixes issues on bulk appointments end date when no repeat times is entered and it would show the previous day as the last appointment date.
> NN-2350 Add last appointment date to add appointment form

- backend/controllers/appointmentsService.js
- backend/controllers/confirmAppointment.js
- backend/controllers/prepostAppoinments.js
- backend/shared/appointmentConstants.js
- backend/tests/confirmAppointments.test.js
- backend/tests/prepostAppointments.test.js
> NN-2348 prepost confirmation

- static/js/main.js
Get the **Last appointment on**  date when the text changes in the **How many appointments do you want to add?** input, rather than waiting until the input loses focus.
> NN-2350 Calculate appointment end date on keydown of text input

- audit-ci.json
No patch available yet
https://www.npmjs.com/advisories/961
> Add node-sass vulnerability advisory 961 to audit config to allow builds to continue

- backend/api/elite2Api.js
- backend/controllers/prisonerSearch.js
- backend/controllers/prisonerSearchController.js
- backend/routes.js
- backend/tests/prisonerSearch.test.js
- backend/utils/nunjucksSetup.js
- views/prisonerSearch.njk
> NN-2318 prisoner search form

- backend/controllers/search/prisonerSearch.js
- backend/tests/prisonerSearch.test.js
- views/prisonerSearch.njk
> NN-2318 Search form sort options and addition of text under header

- backend/controllers/appointments/addCourtAppointment.js
- backend/controllers/appointments/appointmentsService.js
- backend/controllers/appointments/confirmAppointment.js
- backend/controllers/appointments/courtController.js
- backend/controllers/appointments/selectCourtAppointmentCourt.js
- backend/controllers/appointments/selectCourtAppointmentCourtController.js
- backend/controllers/appointments/selectCourtAppointmentRooms.js
- backend/controllers/attendance/existingEventsService.js
- backend/routes.js
- backend/tests/addCourtAppointment.test.js
- backend/tests/selectCourtAppointmentCourt.test.js
- backend/tests/selectCourtAppointmentRooms.test.js
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/SelectCourtAppointmentCourtPage.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/AddCourtAppointmentSpecification.groovy
- views/addAppointment/selectCourtAppointmentCourt.njk
- views/addAppointment/selectCourtAppointmentRooms.njk
> NN-2405 Select court page when date and times are available

- backend/controllers/appointments/confirmAppointment.js
- backend/tests/confirmAppointments.test.js
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/ConfirmVideoLinkCourtPage.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/ConfirmVideoLinkPrisonPage.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/SelectCourtAppointmentCourtPage.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/SelectCourtAppointmentRoomsPage.groovy
- views/addAppointment/selectCourtAppointmentCourt.njk
- views/addAppointment/selectCourtAppointmentRooms.njk
- views/videolinkBookingConfirmHearing.njk
The labels and summaries come from JS objects, so in order to change them, the JS objects needed to be changed/broken down.
> NN-2430: Language and spacing tweaks

- backend/controllers/appointments/appointmentsService.js
- backend/controllers/appointments/confirmAppointment.js
- backend/controllers/appointments/selectCourtAppointmentCourt.js
- backend/tests/confirmAppointments.test.js
- backend/tests/prepostAppointments.test.js
- backend/tests/selectCourtAppointmentRooms.test.js
- backend/utils/nunjucksSetup.js
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/ConfirmVideoLinkCourtPage.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/ConfirmVideoLinkPrisonPage.groovy
- views/addAppointment/selectCourtAppointmentCourt.njk
- views/addAppointment/selectCourtAppointmentRooms.njk
- views/videolinkBookingConfirmHearing.njk
Updates to court video link booking screens with label changes and spacing tweaks.
> Nn 2405 ui tweaks

- backend/controllers/appointments/bulkAppointmentsConfirm.js
- backend/tests/bulkAppointmentsAddDetails.test.js
- backend/tests/dateHelpers.test.js
- src/dateHelpers.js
Fixes a classic JavaScript falsely bug in the buildDateTime function.
> NN-2404 fix build time function

- backend/controllers/appointments/bulkAppointmentsConfirm.js
- backend/tests/bulkAppointmentsAddDetails.test.js
- backend/tests/dateHelpers.test.js
- src/dateHelpers.js
Reverts ministryofjustice/prisonstaffhub#793
> Revert "NN-2404 fix build time function"

- backend/controllers/appointments/addCourtAppointment.js
- backend/utils/nunjucksSetup.js
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/ConfirmVideoLinkCourtPage.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/ConfirmVideoLinkPrisonPage.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/NoAvailabilityPage.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/SelectCourtAppointmentCourtPage.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/AddCourtAppointmentSpecification.groovy
- Fix date regression
- Strengthen and add more integration tests
> NN-2483 fix date regression

- backend/controllers/appointments/viewAppointmentsController.js
- backend/tests/viewAppointmentsController.test.js
- sass/application.scss
- sass/components/_print-link.scss
- views/partials/footer.njk
- views/partials/header.njk
- views/partials/printLink.njk
- views/viewAppointments.njk
> NN-2387 Print link and styles for view appointments page

- views/addAppointment/selectCourtAppointmentRooms.njk
> NN-2479 Change label wording on select rooms page

- backend/config.js
- backend/controllers/appointments/requestBooking.js
- backend/controllers/appointments/requestBookingController.js
- backend/routes.js
- backend/tests/requestBooking.test.js
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/RequestBookingConfirmationPage.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/RequestBookingEnterOffenderDetails.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/RequestBookingSelectCourtPage.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/RequestBookingStartPage.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/GlobalSearchSpecification.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/RequestCourtBookingSpecification.groovy
- views/requestBooking/offenderDetails.njk
- views/requestBooking/requestBooking.njk
- views/requestBooking/requestBookingConfirmation.njk
- views/requestBooking/selectCourt.njk
Just want to get this into master as it's all hanging together now.
The following is left todo:
- Availability checks
- Summary UI tweaks
- Prison name and email config
- Code tidy up
> NN-2376 request court booking part 1

- backend/controllers/search/prisonerSearchResultsController.js
- backend/tests/prisonerSearchResultsController.test.js
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/PrisonerSearchResultsPage.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/PrisonerSearchSpecification.groovy
- sass/application.scss
- views/prisonerSearchResults.njk
- Change Last name, First name to First name Last Name
- Change Prison no. to Prison number
- Change DOB Format to `Day Month Year`
- Remove search info and change to text to `Showing X prisoner(s)`
- Add visually hidden text for screen readers to booking link
> NN-2437 Changes to prisoner search results page

- backend/controllers/appointments/requestBooking.js
- backend/controllers/appointments/requestBookingController.js
- backend/tests/requestBooking.test.js
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/RequestCourtBookingSpecification.groovy
- views/requestBooking/offenderDetails.njk
- views/requestBooking/requestBooking.njk
- views/requestBooking/requestBookingConfirmation.njk
- views/requestBooking/selectCourt.njk
- Fix the order of pages within request court booking journey
- Add visual spacing between related data
> NN-2376 request court booking part2

- backend/controllers/appointments/requestBooking.js
- backend/tests/requestBooking.test.js
Provide validation messages for when only part of the time has been entered.
> NN-2376 fix validation message

- views/prisonerSearch.njk
Reverts ministryofjustice/prisonstaffhub#837
> Revert "NN-2376 remove request booking link"

- backend/controllers/appointments/selectCourtAppointmentCourt.js
- backend/tests/selectCourtAppointmentCourt.test.js
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/AddCourtAppointmentSpecification.groovy
> NN-2514 Remove pre and post info from court selection page when not selected

- backend/utils.js
- backend/utils.test.js
- src/AlertFlags/AlertFlags.js
- src/AlertFlags/AlertFlags.scss
- src/FullFlags/Flags.js
- src/FullFlags/Flags.test.js
- src/FullFlags/fullFlags.scss
Also adjusted the order alerts appear, alphabetically
> NN-2525 Add quarantined alert flag

- backend/controllers/retentionReasons.js
- backend/routes.js
- backend/routes/retentionReasonsRouter.js
- backend/tests/retentionReasons.test.js
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/RetentionReasonsPage.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/RetentionReasonsSpecification.groovy
- sass/application.scss
- sass/components/_offender-basic-details.scss
- views/retentionReasons.njk
Currently this has no functionality, it is just
styling and setting up some basic tests.
> GDPR-78 Adding retention reasons page

- sass/components/_offender-basic-details.scss
- views/retentionReasons.njk
I've done what I can to reduce the use of css for the offender banner.  There is still a remaining flexbox layout configured using css since nothing that I have tried using layouts here: https://design-system.service.gov.uk/styles/layout/ have worked as required.
> GDPR-78 Removing unnecessary css

- backend/routes/appointments/requestBookingRouter.js
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/RequestBookingPrisonerNotListedPage.groovy
- views/requestBooking/prisonerNotListed.njk
Page is not linked-to from anywhere yet, part of a larger journey.
> NN-2524: Add prisoner not listed request booking info page

- views/prisonerSearch.njk
- Show Prisoner not listed link for 0 results
- Allow 'Select' to remain an option from prisoner dropdown
> NN-2511 Minor UI updates to prisoner search page

- backend/controllers/attendance/attendanceStatistics.js
- backend/tests/attendanceStatistics.test.js
- sass/application.scss
- views/attendanceStatisticsOffendersList.njk
> Nn 2529 add suspended whereabouts offender stats lists

- backend/tests/attendanceStatistics.test.js
- views/attendanceStatistics.njk
> NN-2526: Include suspended count to attendance statistics dashboard

- backend/routes.js
- backend/routes/appointments/viewAppointmentsRouter.js
- backend/tests/viewAppointmentsController.test.js
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/mockapis/OauthApi.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/ViewAppointmentsSpecification.groovy
- views/viewAppointments.njk
> NN-2539 display created by user

- backend/api/elite2Api.js
- backend/api/keyworkerApi.js
- backend/apis.js
- backend/config.js
- backend/controllers/prisonerProfile/prisonerQuickLook.js
- backend/routes.js
- backend/routes/prisonerProfileRouter.js
- backend/services/prisonerProfileService.js
- backend/tests/prisonerProfileService.test.js
- backend/tests/prisonerQuickLook.test.js
- backend/utils/nunjucksSetup.js
- helm_deploy/prison-staff-hub/templates/_envs.tpl
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- sass/application.scss
- sass/components/prisonerProfile/_prisoner-profile-header.scss
- views/prisonerProfile/partials/prisonerProfileHeader.njk
- views/prisonerProfile/prisonerQuickLook.njk
Still a WIP but want to keep the PRs sensible.
To do:
- Add alerts
- Add links to other pages (IEP, Add Case note etc)
- Responsive layout
Also added Main offence but this will be completed fully as part of NN-2457.
> NN-2552 Initial commit of new prisoner profile header

- backend/services/prisonerProfileService.js
- backend/shared/alertFlagValues.js
- backend/tests/prisonerProfileService.test.js
- sass/application.scss
- sass/components/_alert-flags.scss
- sass/components/prisonerProfile/_prisoner-profile-header.scss
- views/prisonerProfile/partials/prisonerProfileHeader.njk
> NN-2552 Add alerts to prisoner header

- backend/config.js
- backend/controllers/prisonerProfile/prisonerQuickLook.js
- backend/routes.js
- backend/routes/prisonerProfileRouter.js
- backend/services/prisonerProfileService.js
- backend/tests/prisonerProfileService.test.js
- backend/tests/prisonerQuickLook.test.js
- helm_deploy/prison-staff-hub/templates/_envs.tpl
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- sass/components/prisonerProfile/_prisoner-profile-header.scss
- views/prisonerProfile/partials/prisonerProfileHeader.njk
> NN-2552 Add prisoner profile header links for Incentive Level and Categorisation

- backend/api/elite2Api.js
- backend/config.js
- backend/controllers/prisonerProfile/prisonerQuickLook.js
- backend/services/prisonerProfileService.js
- backend/tests/prisonerProfileService.test.js
- backend/tests/prisonerQuickLook.test.js
- config/jest/setupTests.js
- helm_deploy/prison-staff-hub/templates/_envs.tpl
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- sass/components/prisonerProfile/_prisoner-profile-header.scss
- views/prisonerProfile/partials/prisonerProfileHeader.njk
Large screen (desktop):
In between desktop and mobile (tablet):
Small screen (mobile):
> NN-2552 Prisoner profile buttons and layout

- backend/api/elite2Api.js
- backend/controllers/prisonerImage.js
- backend/controllers/prisonerProfile/prisonerFullImage.js
- backend/controllers/prisonerProfile/prisonerQuickLook.js
- backend/routes/prisonerProfileRouter.js
- backend/tests/prisonerFullImage.test.js
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/mockapis/Elite2Api.groovy
- sass/application.scss
- sass/components/prisonerProfile/_prisoner-full-image.scss
- views/prisonerProfile/partials/prisonerProfileHeader.njk
- views/prisonerProfile/prisonerFullImage.njk
> NN-2552 Add route for full size prisoner image

- backend/api/elite2Api.js
- backend/controllers/prisonerProfile/prisonerQuickLook.js
- backend/tests/prisonerQuickLook.test.js
- backend/utils.js
- views/prisonerProfile/prisonerQuickLook.njk
> NN-2457 Add Offence, Money and Personal sections to new quick look

- backend/api/elite2Api.js
- backend/api/keyworkerApi.js
- backend/controllers/incentiveLevelDetails.js
- backend/controllers/prisonerProfile/prisonerQuickLook.js
- backend/shared/formatAward.js
- backend/tests/incentiveLevelDetails.test.js
- backend/tests/prisonerQuickLook.test.js
- backend/utils.js
- backend/utils/nunjucksSetup.js
- sass/_govuk-overrides.scss
- sass/application.scss
- sass/components/prisonerProfile/_prisoner-profile-header.scss
- views/prisonerProfile/prisonerQuickLook.njk
> NN-2457 Add case note, adjudications and visits data to quick look

- backend/api/elite2Api.js
- backend/controllers/prisonerProfile/prisonerQuickLook.js
- backend/shared/filterActivitiesByPeriod.js
- backend/shared/formatEvent.js
- backend/tests/prisonerQuickLook.test.js
- sass/_typography.scss
- sass/application.scss
- views/prisonerProfile/macros/scheduledActivities.njk
- views/prisonerProfile/prisonerQuickLook.njk
> NN-2457 Add todays scheduled events to prisoner profile quick look

- backend/controllers/prisonerProfile/prisonerQuickLook.js
- backend/controllers/search/prisonerSearch.js
- backend/tests/prisonerQuickLook.test.js
- backend/tests/prisonerSearch.test.js
- sass/_typography.scss
- sass/application.scss
- sass/components/_buttons.scss
- sass/components/prisonerProfile/_prisoner-profile-header.scss
- views/prisonerProfile/partials/prisonerProfileHeader.njk
- views/prisonerProfile/prisonerQuickLook.njk
- views/prisonerSearch.njk
- Replace `visually-hidden` with `govuk-visually-hidden`
- Added custom `govuk-button--link` button style
- Used `govuk-colours`
- Added links to various sections under each quick look section (some dummy for now)
> NN-2457 Prisoner profile updates

- views/prisonerProfile/prisonerQuickLook.njk
> NN-2457 Add offender management section with link to probation

- views/prisonerSearch.njk
> NN-2510 Hide/remove column heading text from prisoner search results table

- sass/components/_alert-flags.scss
- sass/components/prisonerProfile/_prisoner-profile-header.scss
- views/prisonerProfile/macros/alertFlags.njk
- views/prisonerProfile/macros/categoryFlag.njk
- views/prisonerProfile/partials/prisonerProfileHeader.njk
Also moved alert flags into a reusable macro.
> NN-2457 Add styling to Cat A categories

- backend/controllers/prisonerProfile/prisonerQuickLook.js
- backend/services/prisonerProfileService.js
- backend/shared/logErrorAndContinue.js
- backend/tests/prisonerProfileService.test.js
- sass/components/prisonerProfile/_prisoner-profile-header.scss
Before:
After:
Also fixed display issue with width of content.
> NN-2457 Still show prisoner profile header data if some data is not available

- backend/api/elite2Api.js
- backend/controllers/attendance/attendanceStatistics.js
- backend/routes.js
- backend/tests/attendanceStatistics.test.js
- sass/application.scss
- views/attendanceStatistics.njk
- views/attendanceStatisticsOffendersList.njk
- views/attendanceStatisticsSuspendedList.njk
Add link to the dashboard stats through to a new page that lists the suspended offenders for the period(s) and date range and their attendance outcome.
> Nn 2528 suspended list

- backend/controllers/prisonerProfile/prisonerPersonal.js
- backend/routes/prisonerProfileRouter.js
- backend/tests/prisonerPersonal.test.js
- backend/tests/prisonerQuickLook.test.js
- sass/_govuk-overrides.scss
- views/prisonerProfile/macros/prisonerAccordionSection.njk
- views/prisonerProfile/prisonerPersonal.njk
Actual content to be covered by multiple tickets.
> NN-2578 Layout for personal tab/page

- sass/_govuk-overrides.scss
- views/prisonerProfile/prisonerPersonal.njk
> NN-2578 Handle borders on accordions split over grid columns

- backend/api/elite2Api.js
- backend/controllers/prisonerProfile/prisonerPersonal.js
- backend/routes/prisonerProfileRouter.js
- backend/tests/prisonerPersonal.test.js
- backend/tests/prisonerQuickLook.test.js
- views/prisonerProfile/prisonerPersonal.njk
> NN-2581 Add identifiers to personal page

- backend/controllers/attendance/attendanceStatistics.js
- backend/tests/attendanceStatistics.test.js
- views/attendanceStatistics.njk
> Nn 2574 attendance reason stats ui tweaks

- backend/api/elite2Api.js
- backend/api/keyworkerApi.js
- backend/controllers/prisonerProfile/prisonerPersonal.js
- backend/services/prisonerProfileService.js
- backend/tests/prisonerPersonal.test.js
- backend/utils.js
- backend/utils.test.js
- views/prisonerProfile/prisonerPersonal.njk
**With:**
**Without:**
Also added a `putLastNameFirst` util function as I feel like I do this loads and will only be doing it more.
> NN-2580 Add alias section to personal page

- backend/controllers/prisonerProfile/prisonerPersonal.js
- backend/tests/prisonerPersonal.test.js
- backend/utils/nunjucksSetup.js
- views/prisonerProfile/prisonerPersonal.njk
Hide any identifiers without a value, except for PNC which displays **Not entered**:
> NN-2581 Hide identifiers with no value except for PNC

- backend/api/elite2Api.js
- backend/controllers/prisonerProfile/prisonerPersonal.js
- backend/tests/prisonerPersonal.test.js
- views/prisonerProfile/prisonerPersonal.njk
**If all entered:**
**If some entered**
**If all not entered:**
> NN-2584 Add physical characteristics to personal

- backend/api/elite2Api.js
- backend/controllers/prisonerProfile/prisonerPersonal.js
- backend/tests/prisonerPersonal.test.js
- sass/_govuk-overrides.scss
- views/prisonerProfile/prisonerPersonal.njk
Images to come later in separate PR.
> NN-2585 distinguishing marks

- backend/api/whereaboutsApi.js
- backend/controllers/attendance/attendanceStatistics.js
- backend/tests/attendanceStatistics.test.js
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/mockapis/Elite2Api.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/mockapis/WhereaboutsApi.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/AttendanceSuspendedPage.groovy
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/AttendanceStatsDashboardSpecification.groovy
- views/attendanceStatistics.njk
Also updates the suspended endpoint to use new whereabouts api endpoint, reducing complexity.
> Nn 2609 fix suspended link

- backend/api/elite2Api.js
- backend/controllers/prisonerProfile/prisonerPersonal.js
- backend/tests/prisonerPersonal.test.js
- views/prisonerProfile/prisonerPersonal/partials/property.njk
- views/prisonerProfile/prisonerPersonal/prisonerPersonal.njk
**Without property:**
**With property:**
> NN-2597 Add personal property

- views/prisonerProfile/prisonerPersonal/partials/property.njk
> NN-2597 Show Not entered text for any missing property info

- backend/controllers/appointments/bulkAppointmentsUpload.js
- backend/controllers/offender-loader.js
- backend/routes/appointments/bulkAppointmentsUploadRouter.js
- backend/tests/bulkAppointmentsUpload.test.js
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/BulkAppointmentsSpecification.groovy
- sass/application.scss
- static/js/main.js
- views/bulkAppointmentsAddDetails.njk
- views/bulkAppointmentsConfirm.njk
- views/bulkAppointmentsInvalidNumbers.njk
- views/uploadOffenders.njk
Reverts ministryofjustice/prisonstaffhub#973
> Revert "Nn 2541 last appointment and cell location"

- backend/controllers/appointments/bulkAppointmentsUpload.js
- backend/controllers/offender-loader.js
- backend/routes/appointments/bulkAppointmentsUploadRouter.js
- backend/tests/bulkAppointmentsUpload.test.js
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/BulkAppointmentsSpecification.groovy
- sass/application.scss
- static/js/main.js
- views/bulkAppointmentsAddDetails.njk
- views/bulkAppointmentsConfirm.njk
- views/bulkAppointmentsInvalidNumbers.njk
- views/uploadOffenders.njk
Reverts ministryofjustice/prisonstaffhub#976
> Revert "Revert "Nn 2541 last appointment and cell location""

- backend/api/elite2Api.js
- backend/controllers/prisonerProfile/personalViewModels/activeContactsViewModel.js
- backend/controllers/prisonerProfile/personalViewModels/index.js
- backend/controllers/prisonerProfile/prisonerPersonal.js
- backend/routes/prisonerProfileRouter.js
- backend/services/personService.js
- backend/tests/personService.test.js
- backend/tests/prisonerPersonal.test.js
- views/prisonerProfile/prisonerPersonal/partials/activeContacts.njk
- views/prisonerProfile/prisonerPersonal/prisonerPersonal.njk
> NN-2583 Active contacts (Personal only)

- backend/api/elite2Api.js
- backend/controllers/prisonerProfile/prisonerQuickLook.js
- backend/tests/prisonerPersonal.test.js
- backend/tests/prisonerQuickLook.test.js
> NN-2620 Return correct nationality value instead of other nationalities on quick look

- backend/controllers/prisonerProfile/personalViewModels/languageViewModel.js
- backend/controllers/prisonerProfile/personalViewModels/languageViewModel.test.js
- backend/tests/prisonerPersonal.test.js
- views/prisonerProfile/prisonerPersonal/partials/languages.njk
- Move business logic out of the view and into the middle tier
> NN-2587 prisoner profile language tidy up

- backend/controllers/prisonerProfile/prisonerPersonal.js
- integration-tests/integration/prisonerProfile/prisonerPersonal.spec.js
- integration-tests/mockApis/elite2.js
- integration-tests/plugins/index.js
- views/prisonerProfile/prisonerPersonal/prisonerPersonal.njk
With data will be separate PR.
> NN-2640 Add personal page integration tests for when there is no data

- backend/controllers/prisonerProfile/personalViewModels/addressesViewModel.js
- backend/tests/prisonerPersonal.test.js
- integration-tests/integration/prisonerProfile/prisonerPersonal.spec.js
- views/prisonerProfile/prisonerPersonal/partials/addresses.njk
> NN-2582 Add address usage types and show primary addresses with future end date

- README.md
- backend/controllers/covid/covidDashboard.js
- backend/controllers/covid/reverseCohortingUnit.js
- backend/routes.js
- backend/services/covidService.js
- backend/tests/covidDashboard.test.js
- backend/tests/covidService.test.js
- backend/tests/reverseCohortingUnit.test.js
- backend/utils.js
- backend/utils/nunjucksSetup.js
- integration-tests/integration/covid/view-reverse-cohorting-list.spec.js
- integration-tests/mockApis/elite2.js
- integration-tests/pages/covid/viewReverseCohortingListPage.js
- integration-tests/plugins/index.js
- views/covid/reverseCohortingUnit.njk
> DCS-513 Adding reverse cohorting screen

- helm_deploy/prison-staff-hub/templates/deployment.yaml
- helm_deploy/prison-staff-hub/templates/ingress.yaml
This reverts commit f6b02e200f919c38379be8862eaab2b6f97228cb.
> Revert "DT-917: Switch out deprecated APIs (#1028)"

- backend/controllers/covid/refusingToShieldController.js
- backend/routes.js
- backend/routes/covidRouter.js
- backend/tests/refusingToShieldController.test.js
- backend/tests/shieldingUnitController.test.js
- integration-tests/integration/covid/view-dashboard.spec.js
- integration-tests/integration/covid/view-refusing-to-shield-list.spec.js
- integration-tests/pages/covid/refusingToShieldPage.js
- views/covid/refusingToShield.njk
Created a new page where user can view all the the prisoners that have refused to shield. 
Access is via the 'view prisoners' link on http://localhost:3002/current-covid-units/
> Dcs 517 refused to shield list

- helm_deploy/prison-staff-hub/templates/deployment.yaml
- helm_deploy/prison-staff-hub/templates/ingress.yaml
Reverts ministryofjustice/prisonstaffhub#1033
> Revert "Revert "DT-917: Switch out deprecated APIs (#1028)""

- integration-tests/integration/covid/view-reverse-cohorting-list.spec.js
- integration-tests/pages/covid/reverseCohortingUnitPage.js
- views/covid/protectiveIsolationUnit.njk
- views/covid/refusingToShield.njk
- views/covid/reverseCohortingUnit.njk
- views/covid/shieldingUnit.njk
was using contents of the a tag which differentiated by offender number rather than name
> DCS-534 Fixing name sort 

- backend/api/elite2Api.js
- backend/controllers/search/prisonerSearch.js
- backend/routes.js
- backend/tests/prisonerSearch.test.js
- backend/tests/videolinkPrisonerSearch.test.js
- backend/utils.js
- integration-tests/integration/search/prisonerSearch.spec.js
- integration-tests/mockApis/elite2.js
- integration-tests/plugins/index.js
- sass/_moj-overrides.scss
- sass/application.scss
- sass/components/_alert-flags.scss
- sass/components/prisonerProfile/_prisoner-profile-header.scss
- sass/components/prisonerSearch/_prisoner-search.scss
- static/js/main.js
- views/prisonerSearch/partials/prisonerSearchForm.njk
- views/prisonerSearch/partials/prisonerSearchList.njk
- views/prisonerSearch/prisonerSearch.njk
> NN-2630 Prisoner search results

- backend/controllers/search/prisonerSearch.js
- backend/tests/prisonerSearch.test.js
- sass/application.scss
- sass/components/prisonerSearch/_prisoner-panel.scss
- sass/components/prisonerSearch/_prisoner-search.scss
- views/prisonerSearch/macros/prisonerPanel.njk
- views/prisonerSearch/partials/prisonerSearchGrid.njk
- views/prisonerSearch/partials/prisonerSearchList.njk
- views/prisonerSearch/partials/prisonerSearchToggles.njk
- views/prisonerSearch/prisonerSearch.njk
> NN-2734 Initial commit of search results grid view

- sass/components/prisonerSearch/_prisoner-search.scss
> NN-2734 Update styles of toggles

- backend/controllers/search/prisonerSearch.js
- backend/routes.js
- backend/routes/prisonerSearchRouter.js
- backend/tests/prisonerSearch.test.js
- integration-tests/integration/search/prisonerSearch.spec.js
- sass/components/prisonerSearch/_prisoner-search.scss
- views/prisonerSearch/partials/prisonerSearchForm.njk
- views/prisonerSearch/partials/prisonerSearchOrderForm.njk
- views/prisonerSearch/prisonerSearch.njk
> NN-2737 Add results ordering

- backend/controllers/prisonerProfile/prisonerAlerts.js
- backend/controllers/prisonerProfile/prisonerQuickLook.js
- backend/tests/prisonerAlerts.test.js
- integration-tests/integration/prisonerProfile/prisonerAlertsPage.spec.js
- integration-tests/integration/prisonerProfile/prisonerQuickLook.spec.js
- integration-tests/mockApis/responses/offenderFullDetails.json
- integration-tests/plugins/index.js
- views/prisonerProfile/partials/prisonerProfileTabs.njk
- views/prisonerProfile/prisonerAlerts.njk
- views/prisonerProfile/prisonerQuickLook/partials/caseNotesAdjudications.njk
- views/prisonerProfile/prisonerQuickLook/prisonerQuickLook.njk
If a prisoner is not in a users caseload and/or a user cannot view an active booking then:
- Hide Case notes tab
- Hide View adjudication history link
- Hide probation docs link
- Hide Create/Edit/Close alert buttons
> NN-2748 Prisoner profile access

- integration-tests/integration/prisonerProfile/prisonerPersonal.spec.js
- views/prisonerProfile/prisonerPersonal/partials/activeContacts.njk
Was **--**
Now **Not entered**
> NN-2758 Change missing values text back to Not entered and add test for active contacts

- backend/controllers/prisonerProfile/personalViewModels/activeContactsViewModel.js
- backend/tests/prisonerPersonal.test.js
- integration-tests/integration/prisonerProfile/prisonerPersonal.spec.js
- views/prisonerProfile/prisonerPersonal/partials/activeContacts.njk
> NN-2766 Show no fixed address for active personal and professional contacts

- backend/controllers/prisonerProfile/prisonerQuickLook.js
- views/prisonerProfile/layouts/prisonerLayout.njk
- views/prisonerProfile/prisonerQuickLook/prisonerQuickLook.njk
Breadcrumb is now the same regardless of tab
> NN-2763 Change breadcrumbs and prevent invalid offender number causing app crash

- backend/api/pathfinderApi.js
- backend/apis.js
- backend/config.js
- backend/controllers/prisonerProfile/prisonerAlerts.js
- backend/controllers/prisonerProfile/prisonerQuickLook.js
- backend/routes.js
- backend/routes/prisonerProfileRouter.js
- backend/services/prisonerProfileService.js
- backend/tests/prisonerProfileService.test.js
- backend/tests/prisonerQuickLook.test.js
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- integration-tests/integration/prisonerProfile/prisonerAlertsPage.spec.js
- integration-tests/integration/prisonerProfile/prisonerPersonal.spec.js
- integration-tests/integration/search/prisonerSearch.spec.js
- integration-tests/mockApis/pathfinder.js
- integration-tests/plugins/index.js
- sass/_govuk-overrides.scss
- views/prisonerProfile/partials/prisonerProfileHeader.njk
> NN-2754 pathfinder links

- backend/api/caseNotesApi.js
- backend/controllers/controller.js
- backend/controllers/prisonerProfile/prisonerCaseNotes.js
- backend/routes.js
- backend/routes/prisonerSearchRouter.js
- backend/services/prisonerProfileService.js
- backend/tests/caseNotesController.test.js
- integration-tests/integration/prisonerProfile/caseNotesPage.spec.js
- integration-tests/pages/prisonerProfile/caseNotePage.js
- src/IncentiveLevelSlipContainer/IncentiveLevelSlipContainer.js
- views/prisonerProfile/prisonerCaseNotes/partials/caseNoteDetailColumn.njk
The Incentive level slip is a shared React component between new-nomis-ui and prisonstaffhub and is used in multiple places. This is a bit of a cheat which means that if you're trying to access the slip from a non-react page, it gets the data from a combination of URL params and api calls.
> Nn 2769 print incentive slip

- backend/controllers/prisonerProfile/sentenceAndReleaseViewModels/courtCasesViewModel.js
- backend/tests/prisonerSentenceAndRelease.test.js
- integration-tests/integration/prisonerProfile/prisonerSentenceAndRelease.spec.js
> Nn 2783 sentence imprisonment length label updates

- integration-tests/integration/prisonerProfile/prisonerVisits.spec.js
- views/prisonerProfile/prisonerVisits/partials/prisonerVisitsSearchForm.njk
- views/prisonerProfile/prisonerVisits/prisonerVisits.njk
> NN-2460 Add apostrophe back in to prisoner name and add View by fieldset legend

- backend/controllers/prisonerProfile/personalViewModels/activeContactsViewModel.js
- backend/tests/prisonerVisits.test.js
Also updates a test that requires age calculation. Turns out it was someone's birthday over the weekend.
> NN-2771: Fix bug when address type is missing

- integration-tests/integration/prisonerProfile/caseNotesPage.spec.js
- integration-tests/pages/prisonerProfile/caseNotePage.js
- views/prisonerProfile/prisonerCaseNotes/caseNotes.njk
> NN-2759: Show message when there are no case notes

- backend/controllers/alert.js
- backend/controllers/prisonerProfile/prisonerAlerts.js
- backend/tests/alert.test.js
- backend/tests/prisonerAlerts.test.js
- integration-tests/integration/prisonerProfile/prisonerAlertsPage.spec.js
- sass/components/prisonerProfile/_prisoner-profile-header.scss
- src/CreateAlert/CreateAlertContainer.js
- src/routes.js
- views/editAlertForm.njk
- views/prisonerProfile/partials/prisonerProfileHeader.njk
- views/prisonerProfile/prisonerAlerts.njk
- Change date formats to `D MMMM YYYY`
- Change name format to First name Last name
- **Edit** is now **Change**
- Right-aligned **Change or close** button
- Added Prisoner number to change or close form page
> NN-2765 UI and wording tweaks for alerts

- integration-tests/integration/prisonerProfile/prisonerQuickLook.spec.js
- views/prisonerProfile/partials/prisonerProfileHeader.njk
> NN-2765 Change link to alerts in profile header

- backend/setupWebSecurity.js
- package.json
based on this: https://helmetjs.github.io/docs/nocache/
> DCS-579 Moving away from deprecated nocache and moving to module

- backend/controllers/prisonerProfile/personalViewModels/personalDetailsViewModel.js
- backend/tests/prisonerPersonal.test.js
- integration-tests/integration/prisonerProfile/prisonerPersonal.spec.js
> NN-2821: Include ethnicity code in new profile page

- backend/controllers/search/prisonerSearch.js
- backend/tests/prisonerSearch.test.js
- sass/_govuk-overrides.scss
- sass/components/prisonerSearch/_prisoner-search.scss
- views/macros/printLink.njk
- views/partials/printLink.njk
- views/prisonerProfile/prisonerSchedule/prisonerSchedule.njk
- views/prisonerSearch/partials/prisonerSearchSummary.njk
- views/prisonerSearch/prisonerSearch.njk
- views/viewAppointments.njk
Also changed print link to a macro so the text and positioning can be changed.
> Nn 2738 prisoner search styles

- backend/controllers/controller.js
- backend/controllers/downloadProbationDocument.js
- backend/controllers/probationDocuments.js
- backend/services/movementsService.js
- backend/tests/downloadProbationDocument.test.js
- backend/tests/probationDocuments.test.js
> NN-2801: Add username to system client API calls

- src/Adjudications/AdjudicationHistory/AdjudicationHistoryContainer.js
- src/Components/Page/Page.js
- src/OffenderPage/OffenderPage.js
- src/OffenderPage/__snapshots__/OffenderPage.test.js.snap
- views/prisonerProfile/prisonerFullImage.njk
So they don't appear in analytics.
> NN-2789 Replace prisoner names with numbers in page titles

- backend/controllers/caseNote.js
- backend/tests/caseNote.test.js
- config/jest/globalSetup.js
- config/jest/setupTests.js
- integration-tests/integration/caseNotes/createCaseNote.spec.js
- package.json
- views/caseNotes/addCaseNoteForm.njk
> NN-2837 Add current date and time as default when adding a case note

- backend/controllers/appointments/requestBooking.js
- backend/controllers/prisonerProfile/personalViewModels/careNeedsViewModel.js
- backend/controllers/videolink/search/videolinkPrisonerSearch.js
- backend/tests/prisonerPersonal.test.js
- backend/tests/videolinkPrisonerSearch.test.js
- prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/VideolinkPrisonerSearchSpecification.groovy
> NN-2703: Use formatted description where present

- backend/controllers/cellMove/viewNonAssociations.js
- backend/tests/cellMove/viewNonAssociations.test.js
> NN-2650: Sort non associations in descending order by effective date

- backend/shared/addressHelpers.js
- backend/tests/prisonerProfessionalContacts.test.js
- integration-tests/integration/prisonerProfile/prisonerProfessionalContacts.spec.js
> NN-2540: Add locality to professional addresses

- backend/controllers/search/prisonerSearch.js
- backend/tests/prisonerSearch.test.js
- integration-tests/integration/search/prisonerSearch.spec.js
- sass/components/_print-link.scss
- sass/components/prisonerSearch/_prisoner-search.scss
- views/prisonerSearch/partials/prisonerSearchForm.njk
- views/prisonerSearch/prisonerSearch.njk
> NN-2832 Prisoner search view all results

- backend/controllers/cellMove/selectLocation.js
- backend/controllers/search/prisonerSearch.js
- backend/services/prisonerProfileService.js
- backend/shared/alertFlagValues.js
- backend/tests/cellMove/selectLocation.test.js
- backend/tests/prisonerProfileService.test.js
- backend/tests/prisonerSearch.test.js
- sass/components/_alert-flags.scss
> NN-2658 Add new risk flags for cell move only

- backend/api/elite2Api.js
- backend/api/whereaboutsApi.js
- backend/controllers/cellMove/cellMoveUtils.js
- backend/controllers/cellMove/selectCell.js
- backend/controllers/cellMove/selectLocation.js
- backend/routes.js
- backend/routes/cellMoveRouter.js
- backend/tests/cellMove/selectLocation.test.js
- integration-tests/integration/cellMove/selectLocation.spec.js
- integration-tests/mockApis/elite2.js
- integration-tests/mockApis/responses/cellAttributes.json
- integration-tests/pages/cellMove/selectLocationPage.js
- integration-tests/plugins/index.js
- views/cellMove/partials/prisonerInformation.njk
- views/cellMove/selectCell.njk
- views/cellMove/selectLocation.njk
> Nn 2843 select location form

- backend/controllers/cellMove/selectCell.js
- backend/controllers/cellMove/selectLocation.js
- backend/controllers/cellMove/viewOffenderDetails.js
- backend/routes/cellMoveRouter.js
- backend/tests/cellMove/viewOffenderDetails.test.js
- integration-tests/integration/cellMove/selectLocation.spec.js
- integration-tests/integration/cellMove/viewOffenderDetails.spec.js
- integration-tests/pages/cellMove/offenderDetailsPage.js
- integration-tests/plugins/index.js
- views/cellMove/offenderDetails.njk
- views/cellMove/partials/prisonerInformation.njk
> Nn 2717 cell move offender details

- sass/components/_alert-flags.scss
- views/macros/alertFlags.njk
- views/prisonerSearch/partials/prisonerSearchList.njk
> NN-2825: Optionally put alerts on new line

- backend/services/prisonerProfileService.js
- backend/tests/prisonerProfileService.test.js
- views/prisonerProfile/partials/prisonerProfileHeader.njk
> NN-2881 Add CSRA last review date to profile header

- views/prisonerProfile/partials/prisonerProfileHeader.njk
Incorrectly put the text on the wrong `headerItem` yesterday.
> NN-2881 Put no last review text in correct place

- .circleci/EbDeployDockerfile
- .circleci/config.yml
- views/covid/notInUnit.njk
> DCS-585 Content updates regarding newly arrived offenders screen

- backend/controllers/cellMove/cellMoveUtils.js
- backend/controllers/cellMove/selectCell.js
- backend/controllers/cellMove/selectLocation.js
- backend/controllers/cellMove/viewCellSharingAssessmentDetails.js
- backend/routes/cellMoveRouter.js
- backend/tests/cellMove/selectLocation.test.js
- backend/tests/cellMove/viewCellSharingRiskAssessment.test.js
- integration-tests/integration/cellMove/selectLocation.spec.js
- integration-tests/integration/cellMove/viewCellSharingRiskAssessmentDetails.spec.js
- integration-tests/mockApis/elite2.js
- integration-tests/pages/cellMove/cellSharingRiskAssessmentDetailsPage.js
- integration-tests/plugins/index.js
- views/cellMove/cellSharingRiskAssessmentDetails.njk
- views/cellMove/partials/prisonerInformation.njk
- views/cellMove/selectLocation.njk
> Nn 2718 csra details page

- backend/api/elite2Api.js
- backend/controllers/cellMove/selectCell.js
- backend/tests/cellMove/selectCell.test.js
- integration-tests/integration/cellMove/selectCell.spec.js
- integration-tests/mockApis/elite2.js
- integration-tests/pages/cellMove/selectCellPage.js
- integration-tests/plugins/index.js
- views/cellMove/partials/subLocationsSelect.njk
- views/cellMove/selectCell.njk
- Filter by attribute
- Show different default sub location dropdown values depending on the location value
- Added initial cypress test
> NN-2897 cell filter by attribute

- backend/controllers/cellMove/selectCell.js
- backend/tests/cellMove/selectCell.test.js
- views/cellMove/partials/prisonerInformation.njk
- views/cellMove/selectCell.njk
- views/cellMove/selectLocation.njk
> NN-2898 Add table for available cells

- backend/api/elite2Api.js
- backend/controllers/prisonerProfile/prisonerCellHistory.js
- backend/routes/prisonerProfileRouter.js
- backend/tests/prisonerCellHistory.test.js
- backend/utils.js
- integration-tests/integration/prisonerProfile/prisonerCellHistory.spec.js
- integration-tests/mockApis/elite2.js
- integration-tests/pages/prisonerProfile/prisonerCellHistoryPage.js
- integration-tests/plugins/index.js
- sass/components/_cell-move.scss
- views/prisonerProfile/prisonerCellHistory.njk
> Nn 1180 prisoner location history

- integration-tests/integration/cellMove/selectCell.spec.js
- integration-tests/pages/cellMove/selectCellPage.js
- views/cellMove/selectCell.njk
> NN-2898 Add a couple of integration tests for cell swap results

- backend/controllers/cellMove/selectCell.js
- backend/tests/cellMove/selectCell.test.js
- backend/utils.js
- integration-tests/integration/cellMove/selectCell.spec.js
- integration-tests/mockApis/elite2.js
- integration-tests/plugins/index.js
- views/cellMove/selectCell.njk
> NN-2899 display cell occupants (part 1)

- backend/controllers/cellMove/selectCell.js
- backend/tests/cellMove/selectCell.test.js
- integration-tests/integration/cellMove/selectCell.spec.js
- views/cellMove/selectCell.njk
> NN-2899 cell occupants part2

- helm_deploy/prison-staff-hub/templates/ingress.yaml
Reverts ministryofjustice/prisonstaffhub#1232
> Revert "NN-2906: Update ingress controller class name"

- backend/api/elite2Api.js
- backend/controllers/prisonerProfile/prisonerCellHistory.js
- backend/controllers/prisonerProfile/prisonerLocationHistory.js
- backend/routes/prisonerProfileRouter.js
- backend/tests/prisonerCellHistory.test.js
- backend/tests/prisonerLocationHistory.test.js
- backend/tests/prisonerProfessionalContacts.test.js
- backend/utils.js
- views/prisonerProfile/prisonerCellHistory.njk
- views/prisonerProfile/prisonerLocationHistory.njk
> NN-2883 Location sharing history

- integration-tests/integration/prisonerProfile/prisonerCellHistory.spec.js
- integration-tests/integration/prisonerProfile/prisonerLocationHistory.spec.js
- integration-tests/mockApis/elite2.js
- integration-tests/pages/prisonerProfile/prisonerLocationHistoryPage.js
- integration-tests/plugins/index.js
- views/prisonerProfile/prisonerLocationHistory.njk
With history:
Without history:
> NN-2883 Integration tests for location history page

- backend/controllers/cellMove/selectCell.js
- backend/tests/cellMove/selectCell.test.js
- integration-tests/integration/cellMove/selectCell.spec.js
- integration-tests/pages/cellMove/selectCellPage.js
- sass/components/_alert-flags.scss
- views/cellMove/selectCell.njk
>  NN-2900-non-association-warnings

- backend/controllers/cellMove/moveValidation.js
- backend/routes/cellMoveRouter.js
- backend/tests/cellMove/moveValidation.test.js
- backend/utils.js
- integration-tests/integration/appointments/addAppointment.spec.js
- integration-tests/integration/appointments/addBulkAppointments.spec.js
- integration-tests/integration/cellMove/moveValidation.spec.js
- integration-tests/mockApis/elite2.js
- integration-tests/pages/cellMove/moveValidationPage.js
- integration-tests/plugins/index.js
- views/cellMove/confirmation.njk
- views/cellMove/moveValidation.njk
- views/cellMove/selectCell.njk
More comprehensive integration tests coming in a separate PR
> Nn 2716 cell move conflict page

- backend/controllers/cellMove/cellMoveConfirmation.js
- backend/controllers/cellMove/moveValidation.js
- backend/routes/cellMoveRouter.js
- backend/tests/cellMove/cellMoveConfirmation.test.js
- integration-tests/integration/cellMove/cellMoveConfirmation.spec.js
- integration-tests/integration/cellMove/confirmCellMove.spec.js
- integration-tests/pages/cellMove/cellMoveConfirmationPage.js
- views/cellMove/confirmCellMove.njk
- views/cellMove/confirmation.njk
> NN-2715 cell move confirmation

- backend/api/elite2Api.js
- backend/api/whereaboutsApi.js
- backend/controllers/cellMove/selectCell.js
- backend/log.js
- backend/tests/cellMove/selectCell.test.js
- integration-tests/integration/cellMove/selectCell.spec.js
- integration-tests/mockApis/whereabouts.js
- integration-tests/pages/cellMove/selectCellPage.js
- integration-tests/plugins/index.js
- Show the non association warning when there is an non association on the same residential unit.
> NN-2925 show non association warning

- backend/controllers/prisonerProfile/prisonerCellHistory.js
- backend/routes/prisonerProfileRouter.js
- backend/tests/prisonerCellHistory.test.js
- integration-tests/integration/prisonerProfile/prisonerCellHistory.spec.js
- integration-tests/pages/prisonerProfile/prisonerCellHistoryPage.js
- views/prisonerProfile/prisonerCellHistory.njk
Make the Change cell button appear conditional on the user having the 'CELL_MOVE' role. The role currently only exists on dev.
> NN-2588: Enable cell move button for users with the role

- backend/controllers/cellMove/cellMoveUtils.js
- backend/controllers/cellMove/selectCell.js
- backend/controllers/cellMove/selectLocation.js
- backend/routes.js
- backend/routes/cellMoveRouter.js
- backend/tests/cellMove/selectCell.test.js
- backend/tests/cellMove/selectLocation.test.js
- integration-tests/integration/cellMove/selectCell.spec.js
- integration-tests/integration/cellMove/selectLocation.spec.js
- integration-tests/mockApis/auth.js
- integration-tests/mockApis/elite2.js
If a user is trying to access cell move for an offender that's not in one of their case loads, take them to the page not found page instead.
> Nn 2905 cell move access restriction

- backend/controllers/cellMove/cellNotAvailable.js
- backend/controllers/cellMove/confirmCellMove.js
- backend/routes/cellMoveRouter.js
- backend/tests/cellMove/cellNotAvailable.test.js
- backend/tests/cellMove/confirmCellMove.test.js
- integration-tests/integration/cellMove/cellNotAvailable.spec.js
- integration-tests/pages/cellMove/cellNotAvailablePage.js
- views/cellMove/cellNotAvailable.njk
> NN-2894 cell no longer available

- src/routes.js
> NN-2946: Fix display of what's new breadcrumb

- package-lock.json
- package.json
- views/partials/footer.njk
> NN-2955 Upgrade new-nomis-shared which has footer with Support link removed

- integration-tests/integration/cellMove/selectLocation.spec.js
- sass/_horizontal-content.scss
- sass/application.scss
- sass/components/_cell-move.scss
- views/cellMove/partials/prisonerInformation.njk
- views/cellMove/selectCell.njk
- views/cellMove/selectLocation.njk
- views/prisonerProfile/prisonerCellHistory.njk
- views/prisonerProfile/prisonerLocationHistory.njk
> NN-2948 Update prisoner information UI to be better across all screen sizes

- backend/services/adjudicationHistory.js
- backend/tests/adjudicationHistory.test.js
Currently we show the first charge for an adjudication, this is to change it so we show the final one.
> NN-2979: Update to use the last recorded charge for an adjudication

- backend/services/adjudicationHistory.js
- backend/tests/adjudicationHistory.test.js
Reverts ministryofjustice/prisonstaffhub#1305
> Revert "NN-2979: Update to use the last recorded charge for an adjudication"

- backend/services/adjudicationHistory.js
- backend/tests/adjudicationHistory.test.js
Reverts ministryofjustice/prisonstaffhub#1306
> Revert "Revert "NN-2979: Update to use the last recorded charge for an adjudication""

- backend/controllers/prisonerProfile/prisonerChangeIncentiveLevelDetails.js
- backend/routes/prisonerProfileRouter.js
- backend/tests/prisonerChangeIncentiveLevelDetails.test.js
- integration-tests/integration/prisonerProfile/prisonerChangeIncentiveLevelDetails.spec.js
- integration-tests/integration/prisonerProfile/prisonerIncentiveLevelDetails.spec.js
- integration-tests/mockApis/elite2.js
- integration-tests/plugins/index.js
- views/prisonerProfile/prisonerChangeIncentiveLevelDetails.njk
- views/prisonerProfile/prisonerIncentiveLevelDetails.njk
Deletion of old files to follow in separate PR.
> NN-2974 Incentive level change form

- backend/controllers/establishmentRoll/currentlyOut.js
- backend/routes/establishmentRollRouter.js
- backend/tests/establishmentRoll/currentlyOut.test.js
- integration-tests/integration/establishmentRollCount/currentlyOut.spec.js
- views/establishmentRoll/currentlyOut.njk
Can't delete the react yet as it is used by the Total currently out page as well.
> NN-2986: Move Currently out out of React

- sass/_horizontal-content.scss
- sass/_print.scss
- sass/application.scss
- sass/components/_establishment-roll.scss
- views/establishmentRoll/dashboard.njk
> NN-1843 Print view for establishment roll

- views/establishmentRoll/dashboard.njk
> NN-1843 Add print link to establishment roll page

- backend/routes/appointments/viewAppointmentsRouter.js
- backend/tests/viewAppointmentsController.test.js
- integration-tests/integration/appointments/viewAppointments.spec.js
- views/viewAppointments.njk
Add prisoner cell location column and update some content.
> NN-2931 View appointments updates

- backend/setupWebSecurity.js
- package.json
This is part of helmet so doesn't need to be registered as separate middleware
> Removing hsts dependency

- backend/routes.js
- backend/setupBvlRoutes.js
This needs to be available when VLB is disabled in prison staff hub
> DCS-667 adding missing route

- backend/controllers/cellMove/moveValidation.js
- backend/tests/cellMove/moveValidation.test.js
- package-lock.json
- package.json
- views/cellMove/moveValidation.njk
- views/cellMove/selectCell.njk
> NN-3036 Add breadcrumb to cell move review risks page

- integration-tests/integration/search/prisonerSearch.spec.js
- views/prisonerSearch/partials/prisonerSearchList.njk
- views/prisonerSearch/prisonerSearch.njk
> NN-3015 Show category A as flag in prisoner search results

- backend/api/prisonApi.js
- backend/controllers/prisonerProfile/prisonerFinances/prisonerDamageObligations.js
- backend/routes/prisonerProfileRouter.js
- backend/tests/prisonerDamageObligations.test.js
- integration-tests/integration/prisonerProfile/prisonerDamageObligations.spec.js
- integration-tests/mockApis/prisonApi.js
- integration-tests/plugins/index.js
- views/prisonerProfile/prisonerFinance/damageObligations.njk
- views/prisonerProfile/prisonerFinance/layouts/prisonerFinanceLayout.njk
- views/prisonerProfile/prisonerFinance/partials/prisonerFinanceTabs.njk
> NN-3048 Add damage obligations page

- backend/api/whereaboutsApi.js
- backend/controllers/cellMove/confirmCellMove.js
- backend/routes.js
- backend/routes/cellMoveRouter.js
- backend/setupWebSecurity.js
- backend/tests/cellMove/confirmCellMove.test.js
- integration-tests/integration/cellMove/confirmCellMove.spec.js
- integration-tests/integration/cellMove/moveValidation.spec.js
- integration-tests/mockApis/caseNotes.js
- integration-tests/mockApis/prisonApi.js
- integration-tests/pages/cellMove/confirmCellMovePage.js
- integration-tests/plugins/index.js
- views/cellMove/confirmCellMove.njk
> NN-3018 capture cell move reason

- backend/config.js
- backend/setupBvlRoutes.js
- backend/tests/setupBvlRoutes.test.js
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
Also moving flag out of feature flag section as this was leading to strange react errors (This flag isn't used by react anyway)
> DCS-677 Enabling feature flag for BVL redirect

- backend/api/whereaboutsApi.js
- backend/controllers/cellMove/confirmCellMove.js
- backend/tests/cellMove/confirmCellMove.test.js
- integration-tests/integration/cellMove/confirmCellMove.spec.js
Reverts ministryofjustice/prisonstaffhub#1388
> Revert "NN-3018 fix cell move request"

- backend/api/whereaboutsApi.js
- backend/controllers/cellMove/confirmCellMove.js
- backend/routes.js
- backend/routes/cellMoveRouter.js
- backend/tests/cellMove/confirmCellMove.test.js
- integration-tests/integration/cellMove/confirmCellMove.spec.js
- integration-tests/integration/cellMove/moveValidation.spec.js
- integration-tests/mockApis/caseNotes.js
- integration-tests/mockApis/prisonApi.js
- integration-tests/pages/cellMove/confirmCellMovePage.js
- integration-tests/plugins/index.js
- views/cellMove/confirmCellMove.njk
Reverts ministryofjustice/prisonstaffhub#1386
> Revert "NN-3018 capture cell move reason"

- backend/api/whereaboutsApi.js
- backend/controllers/cellMove/confirmCellMove.js
- backend/routes.js
- backend/routes/cellMoveRouter.js
- backend/tests/cellMove/confirmCellMove.test.js
- integration-tests/integration/cellMove/confirmCellMove.spec.js
- integration-tests/integration/cellMove/moveValidation.spec.js
- integration-tests/mockApis/caseNotes.js
- integration-tests/mockApis/prisonApi.js
- integration-tests/pages/cellMove/confirmCellMovePage.js
- integration-tests/plugins/index.js
- views/cellMove/confirmCellMove.njk
Reverts ministryofjustice/prisonstaffhub#1397
> Revert "Revert "NN-3018 capture cell move reason""

- backend/api/whereaboutsApi.js
- backend/controllers/cellMove/confirmCellMove.js
- backend/tests/cellMove/confirmCellMove.test.js
- integration-tests/integration/cellMove/confirmCellMove.spec.js
Reverts ministryofjustice/prisonstaffhub#1396
> Revert "Revert "NN-3018 fix cell move request""

- backend/controllers/prisonerProfile/prisonerCellHistory.js
- backend/tests/prisonerCellHistory.test.js
- integration-tests/integration/prisonerProfile/prisonerCellHistory.spec.js
- integration-tests/pages/prisonerProfile/prisonerCellHistoryPage.js
- views/prisonerProfile/prisonerCellHistory.njk
- Add Moved in by to current location
- Re ordered and re-labeled headings in the cell history tables
- Refactored a bit of the code (see comments)
> NN-3052 Add moved in by to current location on cell history

- backend/api/whereaboutsApi.js
- backend/controllers/appointments/prepostAppoinments.js
- backend/controllers/appointments/selectCourtAppointmentRooms.js
- backend/routes/appointments/selectCourtAppointmentRoomsRouter.js
- backend/tests/prepostAppointments.test.js
- backend/tests/selectCourtAppointmentRooms.test.js
- integration-tests/integration/appointments/addAppointment.spec.js
- integration-tests/integration/appointments/addCourtAppointmentPrison.spec.js
- integration-tests/mockApis/whereabouts.js
- integration-tests/plugins/index.js
Having to update both prison and court side until we are confident with the book service being in prod
> DCS-697 Call new endpoint to book video link appointment

- integration-tests/integration/prisonerProfile/prisonerCellHistory.spec.js
- This test failed locally due to expecting date times to be UTC
> NN-3068 fix prisoner cell history tests

- backend/controllers/prisonerProfile/prisonerQuickLook.js
- backend/tests/prisonerQuickLook.test.js
- views/prisonerProfile/prisonerQuickLook/partials/money.njk
> NN-3072 Temporarily remove links to non existant finance pages

- backend/controllers/cellMove/cellMoveUtils.js
- backend/controllers/cellMove/selectCell.js
- backend/controllers/cellMove/selectLocation.js
- backend/controllers/cellMove/viewNonAssociations.js
- backend/tests/cellMove/selectCell.test.js
- backend/tests/cellMove/selectLocation.test.js
- integration-tests/integration/cellMove/selectCell.spec.js
- integration-tests/integration/cellMove/selectLocation.spec.js
- integration-tests/integration/prisonerProfile/prisonerQuickLook.spec.js
- integration-tests/pages/cellMove/selectCellPage.js
- integration-tests/pages/cellMove/selectLocationPage.js
- views/cellMove/partials/prisonerInformation.njk
> NN-3070 Add number of non associations to top of cell move

- backend/api/prisonApi.js
- backend/api/whereaboutsApi.js
- backend/controllers/cellMove/cellMoveUtils.js
- backend/controllers/cellMove/selectCell.js
- backend/controllers/cellMove/selectLocation.js
- backend/tests/cellMove/selectCell.test.js
- backend/tests/cellMove/selectLocation.test.js
- integration-tests/integration/cellMove/selectLocation.spec.js
- integration-tests/pages/cellMove/selectLocationPage.js
- views/cellMove/selectCell.njk
- views/cellMove/selectLocation.njk
Disregard cell attributes and have All, Single or Multiple options in cell type dropdown and filter based on the `cell.capacity` value.
> NN-3060 cell move filter update

- backend/api/prisonApi.js
- backend/api/whereaboutsApi.js
- backend/controllers/cellMove/cellMoveUtils.js
- backend/controllers/cellMove/selectCell.js
- backend/controllers/cellMove/selectLocation.js
- backend/tests/cellMove/selectCell.test.js
- backend/tests/cellMove/selectLocation.test.js
- integration-tests/integration/cellMove/selectLocation.spec.js
- integration-tests/pages/cellMove/selectLocationPage.js
- views/cellMove/selectCell.njk
- views/cellMove/selectLocation.njk
Reverts ministryofjustice/prisonstaffhub#1406 😢
> Revert "NN-3060 cell move filter update"

- backend/controllers/prisonerProfile/prisonerLocationHistory.js
- backend/tests/helpers.js
- backend/tests/prisonerLocationHistory.test.js
- integration-tests/integration/prisonerProfile/prisonerLocationHistory.spec.js
- integration-tests/mockApis/whereabouts.js
- integration-tests/plugins/index.js
- views/prisonerProfile/prisonerLocationHistory.njk
Reverts ministryofjustice/prisonstaffhub#1405
> Revert "NN-3034: default on 404"

- backend/controllers/prisonerProfile/prisonerLocationHistory.js
- backend/tests/helpers.js
- backend/tests/prisonerLocationHistory.test.js
- integration-tests/integration/prisonerProfile/prisonerLocationHistory.spec.js
- integration-tests/mockApis/whereabouts.js
- integration-tests/plugins/index.js
- views/prisonerProfile/prisonerLocationHistory.njk
Reverts ministryofjustice/prisonstaffhub#1412
> Revert "Revert "NN-3034: default on 404""

- helm_deploy/values-preprod.yaml
Adding:
* HMP Deerbolt
* HMP Durham
* HMP Holme House
* HMP Kirklevington Grange
> DCS-742 Adding new prisons to UoF

- integration-tests/integration/cellMove/searchForCell.spec.js
- integration-tests/integration/cellMove/selectCell.spec.js
- views/cellMove/partials/prisonerInformation.njk
> NN-3089 Remove gender specific wording from cell move cell swap message

- backend/controllers/cellMove/cellMoveUtils.js
- backend/controllers/cellMove/searchForCell.js
- backend/controllers/cellMove/selectCell.js
- backend/tests/cellMove/searchForCell.test.js
- backend/tests/cellMove/selectCell.test.js
- integration-tests/integration/cellMove/searchForCell.spec.js
- integration-tests/pages/cellMove/searchForCellPage.js
- views/cellMove/searchForCell.njk
- views/cellMove/selectCell.njk
> NN-3091 Update cell move search options to filter on Single or Multiple occupancy

- backend/api/prisonApi.js
- backend/controllers/establishmentRoll/dashboard.js
- backend/tests/establishmentRoll/dashboard.test.js
- integration-tests/integration/establishmentRollCount/establishmentRollCountPage.spec.js
- integration-tests/mockApis/prisonApi.js
- integration-tests/plugins/index.js
- sass/components/_establishment-roll.scss
- views/establishmentRoll/dashboard.njk
Added **No cell allocated** value (cwap occupancy) and updated layout.
> NN-2992 Add cswap occupancy number to establishment roll page

- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
:wrench: Enable UoF for prisons in 18th jan roll-out: Add agencyIds of these prisons to Helm configuration files values-preprod.yaml and values-prod.yaml
> DCS-785 use-of-force go live 18th January 2021

- backend/controllers/prisonerProfile/prisonerFinances/prisonerPrivateCash.js
- backend/controllers/prisonerProfile/prisonerFinances/prisonerSpends.js
- backend/routes/prisonerProfileRouter.js
- backend/services/prisonerFinanceService.js
- backend/shared/createTransactionViewModel.js
- backend/tests/prisonerFinanceService.test.js
- backend/tests/prisonerPrivateCash.test.js
- backend/tests/prisonerSpends.test.js
- integration-tests/integration/prisonerProfile/prisonerSpends.spec.js
- views/prisonerProfile/prisonerFinance/layouts/prisonerFinanceLayout.njk
- views/prisonerProfile/prisonerFinance/partials/prisonerFinanceTabs.njk
- views/prisonerProfile/prisonerFinance/privateCash.njk
- views/prisonerProfile/prisonerFinance/spends.njk
> NN-3045 Prisoner spends page

- backend/controllers/prisonerProfile/prisonerFinances/prisonerSavings.js
- backend/routes/prisonerProfileRouter.js
- backend/services/prisonerFinanceService.js
- backend/tests/prisonerSavings.test.js
- integration-tests/integration/prisonerProfile/prisonerPrivateCash.spec.js
- integration-tests/integration/prisonerProfile/prisonerSavings.spec.js
- views/prisonerProfile/prisonerFinance/partials/prisonerFinanceTabs.njk
- views/prisonerProfile/prisonerFinance/savings.njk
> NN-3047 Add prisoner savings page

- backend/controllers/prisonerProfile/prisonerFinances/prisonerPrivateCash.js
- backend/tests/prisonerPrivateCash.test.js
- integration-tests/integration/prisonerProfile/prisonerPrivateCash.spec.js
- views/prisonerProfile/prisonerFinance/partials/prisonerFinanceTabs.njk
- views/prisonerProfile/prisonerFinance/privateCash.njk
- Additional call for `WHF` pending transaction types
- Re-order tabs
- Rename Pending balance to Pending
> NN-3046 Updates to private cash page

- backend/controllers/prisonerProfile/prisonerFinances/prisonerPrivateCash.js
- backend/shared/createTransactionViewModel.js
- backend/tests/prisonerPrivateCash.test.js
- backend/tests/prisonerSavings.test.js
- backend/tests/prisonerSpends.test.js
- integration-tests/integration/prisonerProfile/prisonerPrivateCash.spec.js
- integration-tests/integration/prisonerProfile/prisonerSavings.spec.js
- integration-tests/integration/prisonerProfile/prisonerSpends.spec.js
- views/prisonerProfile/prisonerFinance/privateCash.njk
- views/prisonerProfile/prisonerFinance/savings.njk
- views/prisonerProfile/prisonerFinance/spends.njk
> NN-3143 Show running balance on finance pages

- backend/api/prisonApi.js
- backend/controllers/establishmentRoll/noCellAllocated.js
- backend/routes/establishmentRollRouter.js
- backend/tests/establishmentRoll/noCellAllocated.test.js
- integration-tests/integration/establishmentRollCount/noCellAllocated.spec.js
- integration-tests/mockApis/prisonApi.js
- integration-tests/plugins/index.js
- views/establishmentRoll/dashboard.njk
- views/establishmentRoll/noCellAllocated.njk
> NN-3100 No cell allocated page

- backend/controllers/establishmentRoll/noCellAllocated.js
- backend/routes.js
- backend/routes/establishmentRollRouter.js
- backend/tests/establishmentRoll/noCellAllocated.test.js
- integration-tests/integration/establishmentRollCount/noCellAllocated.spec.js
- views/establishmentRoll/noCellAllocated.njk
**Without role:**
**With role:**
> NN-3100 Only show Allocate cell links if user has cell move role

- backend/config.js
- cypress.env
- helm_deploy/prison-staff-hub/templates/_envs.tpl
- helm_deploy/prison-staff-hub/templates/secrets.yaml
- helm_deploy/secrets-example.yaml
We never send emails to VCC admins in PSH so this stuff can go
> DCS-842 Removing references to VCCs in PSH

- backend/controllers/attendance/attendanceStatistics.js
- backend/tests/attendanceStatistics.test.js
- src/Components/ResultsTable/elements/TotalResults/TotalResults.js
- src/Components/ResultsTable/elements/TotalResults/__snapshots__/TotalResults.test.js.snap
- src/PrisonersUnaccountedFor/PrisonersUnaccountedForSearch.js
- src/ResultsHouseblock/ResultsHouseblock.js
- views/attendanceStatisticsOffendersList.njk
- views/attendanceStatisticsSuspendedList.njk
- views/covid/notInUnit.njk
- views/covid/protectiveIsolationUnit.njk
- views/covid/refusingToShield.njk
- views/covid/reverseCohortingUnit.njk
- views/covid/shieldingUnit.njk
Also add Prisoners listed value to individual attendance reason statistics page.
> NN-3134 Switch font weight on prisoner listed values

- helm_deploy/values-prod.yaml
Copy additional agency ids from values-preprod.yaml USE_OFFORCE_PRISONS to values-prod.yaml
> DCS-855 Use of Force - Go Live Female Estate 16th Feb. 

- backend/controllers/selectActivityLocation.js
- backend/routes.js
- backend/tests/prisonerSchedule.test.js
- backend/tests/selectActivityLocationsController.test.js
- integration-tests/integration/activity/activityList.spec.js
- integration-tests/integration/activity/selectActivityLocation.spec.js
- src/App.js
- src/ResultsActivity/ResultsActivity.js
- src/ResultsActivity/ResultsActivity.test.js
- src/ResultsActivity/ResultsActivityContainer.js
- src/Search/SearchContainer.js
- static/js/select-activity-location.js
- views/selectActivityLocation.njk
- views/selectResidentialLocation.njk
> Nn 3153 add the new select activity location page

- helm_deploy/values-preprod.yaml
13 additional prisons added to values-preprod.yaml
> DCS-862 Add AgencyIds for UoF Release for LTHE region - 23/02/21. 

- views/attendanceStatisticsOffendersList.njk
There aren't any int tests for this page so I'll add some in the next PR
> NN-3186 fix stats page bug

- src/App.js
- src/PrisonersUnaccountedFor/PrisonersUnaccountedForContainer.js
- src/ResultsActivity/ResultsActivityContainer.js
- src/ResultsHouseblock/ResultsHouseblockContainer.js
- static/js/select-activity-location.js
Integration tests coming in next PR
> NN-3200 fix live bug around previous date selection

- backend/services/prisonerProfileService.js
- backend/tests/prisonerProfileService.test.js
- integration-tests/integration/prisonerProfile/prisonerQuickLook.spec.js
- integration-tests/mockApis/responses/offenderFullDetails.json
- views/prisonerProfile/partials/prisonerProfileHeader.njk
Reverts ministryofjustice/prisonstaffhub#1537
> Revert "NN-3115 Update CSRA info in prisoner profile header"

- backend/services/prisonerProfileService.js
- backend/tests/prisonerProfileService.test.js
- integration-tests/integration/prisonerProfile/prisonerQuickLook.spec.js
- integration-tests/mockApis/responses/offenderFullDetails.json
- views/prisonerProfile/partials/prisonerProfileHeader.njk
Reverts ministryofjustice/prisonstaffhub#1541
> Revert "Revert "NN-3115 Update CSRA info in prisoner profile header""

- backend/api/prisonApi.js
- backend/controllers/prisonerProfile/prisonerCsraHistory.js
- backend/routes/prisonerProfileRouter.js
- backend/tests/prisonerCsraHistory.test.js
- integration-tests/integration/prisonerProfile/prisonerCsraHistory.spec.js
- integration-tests/mockApis/prisonApi.js
- integration-tests/plugins/index.js
- views/prisonerProfile/prisonerCsraHistory.njk
Reverts ministryofjustice/prisonstaffhub#1542
> Revert "Revert "NN-3008 CSRA history page""

- backend/api/prisonApi.js
- backend/controllers/prisonerProfile/prisonerCsraHistory.js
- backend/routes/prisonerProfileRouter.js
- backend/tests/prisonerCsraHistory.test.js
- integration-tests/integration/prisonerProfile/prisonerCsraHistory.spec.js
- integration-tests/mockApis/prisonApi.js
- integration-tests/plugins/index.js
- views/prisonerProfile/prisonerCsraHistory.njk
Reverts ministryofjustice/prisonstaffhub#1547
> Revert "Revert NN-3008 CSRA history page"

- backend/services/prisonerProfileService.js
- backend/tests/prisonerProfileService.test.js
- integration-tests/integration/prisonerProfile/prisonerQuickLook.spec.js
- integration-tests/mockApis/responses/offenderFullDetails.json
- views/prisonerProfile/partials/prisonerProfileHeader.njk
Reverts ministryofjustice/prisonstaffhub#1548
> Revert "Revert NN-3115 Update CSRA info in prisoner profile header"

- backend/api/prisonApi.js
- backend/controllers/prisonerProfile/prisonerCsraHistory.js
- backend/controllers/prisonerProfile/prisonerCsraReview.js
- backend/routes/prisonerProfileRouter.js
- backend/tests/prisonerCsraHistory.test.js
- backend/tests/prisonerCsraReview.test.js
- backend/utils.js
- backend/utils/nunjucksSetup.js
- integration-tests/integration/prisonerProfile/prisonerCsraReview.spec.js
- integration-tests/mockApis/prisonApi.js
- integration-tests/plugins/index.js
- views/prisonerProfile/prisonerCsraHistory.njk
- views/prisonerProfile/prisonerCsraReview.njk
CSRA details page:
Link from CSRA history page:
> NN-3114 CSRA details page

- backend/controllers/prisonerProfile/prisonerCsraReview.js
- backend/tests/prisonerCsraReview.test.js
- integration-tests/integration/prisonerProfile/prisonerCsraReview.spec.js
- views/prisonerProfile/prisonerCsraReview.njk
Also updated breadcrumbs with page title and link back to CSRA history
> NN-3114 Update csra reviewed by to add assessment committee

- backend/controllers/cellMove/confirmCellMove.js
- backend/tests/cellMove/confirmCellMove.test.js
- integration-tests/integration/cellMove/confirmCellMove.spec.js
> NN-3189 Apply cell move comment validation to c-swap/create space journey

- backend/api/prisonApi.js
- backend/controllers/prisonerProfile/prisonerCsraReview.js
- backend/services/prisonerProfileService.js
- backend/shared/csraHelpers.js
- backend/tests/prisonerProfileService.test.js
- integration-tests/mockApis/prisonApi.js
- integration-tests/mockApis/responses/offenderFullDetails.json
Use the csraClassificationCode added to the prison-api endpoint for full offender details, instead of the csra prop, which just gave the last result
> Nn 3220 use new csra classification prop

- backend/controllers/prisonerProfile/prisonerCsraHistory.js
- backend/tests/prisonerCsraHistory.test.js
Ensure csra location is 'Not entered' if not set on csra history page
> Nn 3222 location not blank

- backend/controllers/cellMove/confirmCellMove.js
- backend/tests/cellMove/confirmCellMove.test.js
- integration-tests/integration/cellMove/confirmCellMove.spec.js
Reverts ministryofjustice/prisonstaffhub#1578
> Revert "NN-3189 Apply cell move comment validation to c-swap/create space journey"

- backend/controllers/cellMove/viewOffenderDetails.js
- backend/tests/cellMove/viewOffenderDetails.test.js
The prisoner details page still shows CSWAP - it needs to show "No cell allocated"
> NN-3187: Show description if prisoner in temporary location

- backend/controllers/prisonerProfile/prisonerCsraHistory.js
- backend/tests/prisonerCsraHistory.test.js
- integration-tests/integration/prisonerProfile/prisonerCsraHistory.spec.js
We are not going to show incomplete assessments in the CSRA history
> NN-3231 Remove incomplete csras

- backend/api/prisonApi.js
- backend/controllers/recentCellMoves.js
- backend/routes.js
- backend/tests/recentCellMoves.test.js
- integration-tests/integration/recentCellMoves.spec.js
- integration-tests/mockApis/prisonApi.js
- integration-tests/plugins/index.js
- package-lock.json
- views/changeSomeonesCell/recentCellMoves.njk
> NN-3305 cell moves over the last seven days

- backend/api/whereaboutsApi.js
- backend/controllers/cellMove/cellMoveViewResidentialLocation.js
- backend/routes.js
- backend/tests/cellMove/cellMoveViewResidentialLocation.test.js
- integration-tests/integration/cellMove/cellMoveViewResidentialLocation.spec.js
- views/cellMove/cellMoveViewResidentialLocation.njk
> NN-3266: New cell move view residential location page

- backend/api/keyworkerApi.js
- backend/controllers/homepage/homepage.js
- backend/tests/homepageController.test.js
- integration-tests/integration/globalErrorHandling.spec.js
- integration-tests/integration/homepage/homepage.spec.js
- integration-tests/integration/login/login.spec.js
- integration-tests/mockApis/keyworker.js
- integration-tests/plugins/index.js
Reverts ministryofjustice/prisonstaffhub#1636
> Revert "Nn 3321"

- backend/controllers/cellMove/cellMoveTemporaryMove.js
- backend/routes.js
- backend/tests/cellMove/cellMoveTemporaryMove.test.js
- integration-tests/integration/cellMove/cellMoveTemporaryMove.spec.js
- views/cellMove/cellMoveTemporaryMove.njk
> NN-3267: New cell move temporary move page

- views/cellMove/cellMoveTemporaryMove.njk
> NN-3267: New cell move temporary move page appearance fixes

- backend/controllers/cellMove/cellMovePrisonerSearch.js
- backend/tests/cellMove/cellMovePrisonerSearch.test.js
- views/cellMove/cellMovePrisonerSearch.njk
Also. a couple of view fixes already applied to the other pages
> NN-3360: Cell move prisoner search page: No result limit

- backend/controllers/homepage/homepage.js
- backend/tests/homepageController.test.js
- integration-tests/integration/homepage/homepage.spec.js
- integration-tests/pages/homepage/homepagePage.js
> NN-3262 Add role specific cell move task to homepage

- integration-tests/pages/whereabouts/houseblockPage.js
- sass/_horizontal-content.scss
- src/DatePickers/FormDatePicker.js
- src/DatePickers/WhereaboutsDatePicker.js
- src/DatePickers/__snapshots__/FormDatePicker.test.js.snap
- src/ResultsActivity/ResultsActivity.js
- src/ResultsActivity/ResultsActivity.test.js
- src/ResultsHouseblock/ResultsHouseblock.js
- src/ResultsHouseblock/ResultsHouseblock.test.js
> NN-3253 Update activity and houseblock list ui

- backend/api/whereaboutsApi.js
- backend/controllers/whereabouts/whereaboutsHomepage.js
- backend/routes.js
- backend/routes/appointments/viewAppointmentsRouter.js
- backend/tests/viewAppointmentsController.test.js
- backend/tests/whereaboutsHomepage.test.js
- integration-tests/integration/appointments/viewAppointments.spec.js
- integration-tests/mockApis/whereabouts.js
- integration-tests/pages/appointments/viewAppointmentsPage.js
- integration-tests/plugins/index.js
- views/viewAppointments.njk
Also changed url and some UI updates to filter section:
> NN-3348 Add res location filter to appointments screen

- views/viewAppointments.njk
> NN-3348 Restore Added by column header to appointments page

- backend/api/prisonApi.js
- backend/api/whereaboutsApi.js
- backend/controllers/appointmentDetails.js
- backend/routes.js
- backend/routes/appointments/viewAppointmentsRouter.js
- backend/tests/appointmentDetails.test.js
- backend/tests/viewAppointmentsController.test.js
- integration-tests/integration/appointments/viewAppointments.spec.js
- views/appointmentDetails.njk
- views/viewAppointments.njk
New page:
View details link to new page from view all appointments page:
> NN-3349 Add new appointment details page

- backend/controllers/prisonerProfile/prisonerCaseNotes.js
- backend/tests/caseNotesController.test.js
- integration-tests/integration/prisonerProfile/caseNotesPage.spec.js
spec file also includes linting changes
> NN-3410 Use correct author name for case note amendments

- integration-tests/integration/prisonerProfile/prisonerPersonal.spec.js
- views/prisonerProfile/prisonerPersonal/partials/neurodiversity.njk
This PR updates the second line of text in the neurodiversity accordion content.
> NN-3471: updates second line of text

- backend/controllers/prisonerProfile/prisonerChangeIncentiveLevelDetails.js
- backend/tests/prisonerChangeIncentiveLevelDetails.test.js
- integration-tests/integration/prisonerProfile/prisonerChangeIncentiveLevelDetails.spec.js
- views/prisonerProfile/prisonerChangeIncentiveLevelDetails.njk
- views/prisonerProfile/prisonerIncentiveLevelDetails.njk
> NN-3393 Updates to change incentive level page

- backend/controllers/whereabouts/whereaboutsHomepage.ts
This PR changes the order of the whereabouts tiles.
> NN-3446: updates whereabouts tile order

- integration-tests/integration/activity/activityList.spec.js
- integration-tests/integration/homepage/homepage.spec.js
- integration-tests/pages/homepage/homepagePage.js
- integration-tests/pages/whereabouts/activityPage.js
- sass/application.scss
- src/App.js
- src/Components/FeedbackBanner/FeedbackBanner.js
- views/cellMove/cellMoveHomepage.njk
- views/components/feedbackBanner/feedbackBanner.njk
- views/components/feedbackBanner/feedbackBanner.scss
- views/homepage/homepage.njk
- views/partials/footer.njk
- views/whereabouts/whereaboutsHomepage.njk
Appears at the bottom of every page and appends the pathname to the survey url with the source query param.
> NN-3482 feedback banner

- integration-tests/integration/prisonerProfile/prisonerWorkAndSkills.spec.js
- views/prisonerProfile/prisonerWorkAndSkills/prisonerWorkAndSkills.njk
This PR:
- changes the error content on the functional skills section of the Work and Skills tab to match the new DPS standard messaging
> NN-3556 amend error message content and update int test

- backend/api/curious/types/index.d.ts
- backend/controllers/prisonerProfile/prisonerWorkAndSkills.ts
- backend/services/esweService.ts
- backend/tests/esweService.test.ts
- backend/tests/prisonerWorkAndSkills.test.ts
- integration-tests/integration/prisonerProfile/prisonerWorkAndSkills.spec.js
- integration-tests/mockApis/curiousApi.js
- integration-tests/plugins/index.js
- sass/application.scss
- views/prisonerProfile/prisonerWorkAndSkills/partials/learnerLatestAssessments.njk
- views/prisonerProfile/prisonerWorkAndSkills/partials/learningHistory.njk
- views/prisonerProfile/prisonerWorkAndSkills/prisonerWorkAndSkills.njk
Reverts ministryofjustice/prisonstaffhub#1778
> Revert "Revert "Nn 3564 learning history accordion""

- integration-tests/integration/activity/activityList.spec.js
- integration-tests/integration/homepage/homepage.spec.js
- src/Components/FeedbackBanner/FeedbackBanner.js
- views/components/feedbackBanner/feedbackBanner.njk
> NN-3547 Change feedback link content

- backend/api/prisonApi.ts
- backend/controllers/prisonerProfile/prisonerAlerts.ts
- backend/tests/prisonerAlerts.test.ts
- integration-tests/integration/alerts/createAlert.spec.js
- integration-tests/mockApis/prisonApi.js
Old version had possible vulnerabilities in, so new version acts the same but with a different interface the the modern paging model
> Dt 2330 use booking alerts v2

- backend/utils.test.ts
- backend/utils.ts
- integration-tests/integration/prisonerProfile/prisonerPersonal.spec.js
> NN-3420 Update getNamesFromString util to accomodate firstname lastname format

- backend/api/curious/curiousApi.test.ts
- backend/api/curious/curiousApi.ts
- backend/api/curious/types/index.d.ts
- backend/tests/esweService.test.ts
- integration-tests/integration/prisonerProfile/prisonerPersonal.spec.js
- integration-tests/integration/prisonerProfile/prisonerWorkAndSkills.spec.js
This PR:
- changes the type for establishmentId from number to string to follow the change made on the api response
> ESWE-79-type-change-establishmentId

- backend/controllers/amendmentCaseNote.ts
- backend/tests/amendCaseNoteController.test.ts
- integration-tests/integration/caseNotes/case-note-amendments.spec.js
- integration-tests/pages/caseNotes/case-note-amendments-page.js
- static/js/caseNotes.js
- views/amendCaseNote.njk
> DT-2461: ✨ Add in omic open case note warnings to amend case note

- backend/controllers/whereabouts/scheduledMoves.ts
- backend/tests/scheduledMovesController.test.ts
- integration-tests/integration/whereabouts/scheduledMoves.spec.js
- views/whereabouts/partials/courtEvents.njk
- views/whereabouts/partials/releaseEvents.njk
- views/whereabouts/partials/transferEvents.njk
- views/whereabouts/scheduledMoves.njk
- Filter out video link bookings
- Remove Moj sorting for now due to issues with styles on multiple tables
- Add in print link
> NN-1867 filter out video link bookings

- backend/controllers/whereabouts/scheduledMoves.ts
- integration-tests/integration/whereabouts/scheduledMoves.spec.js
- integration-tests/plugins/index.js
- views/macros/holdAgainstTransferAlertLink.njk
- views/macros/holdAgainstTransferDetails.njk
- views/partials/layout.njk
> NN-3686: Added int tests for Scheduled Moves hold-on-transfer modal dialog

- helm_deploy/values-dev.yaml
- helm_deploy/values-prod.yaml
from viewing Welcome service tile for prod env
> DCS-1102 users without NMI caseload not prevented 

- views/prisonerProfile/prisonerWorkAndSkills/prisonerCoursesQualificationsDetails.njk
- views/prisonerProfile/prisonerWorkAndSkills/prisonerWorkInsidePrisonDetails.njk
Change to the way feedback link is displayed
> ESWE-230 Feedback component on all detail pages

- backend/controllers/prisonerProfile/learnerEmployabilitySkillsDetails.ts
- backend/controllers/prisonerProfile/prisonerWorkAndSkills.ts
- backend/controllers/prisonerProfile/unacceptableAbsencesDetails.ts
- backend/routes/prisonerProfileRouter.ts
- backend/services/esweService.ts
- backend/tests/esweService.test.ts
- backend/tests/learnerEmployabilitySkillsDetails.test.ts
- integration-tests/integration/prisonerProfile/employabilitySkillsDetails.spec.js
- views/prisonerProfile/prisonerWorkAndSkills/learnerEmployabilitySkills.njk
- views/prisonerProfile/prisonerWorkAndSkills/prisonerWorkAndSkills.njk
- views/prisonerProfile/prisonerWorkAndSkills/unacceptableAbsencesDetails.njk
> ESWE-228 and ESWE-233 Employability Skills details pages

- .circleci/config.yml
- README.md
- package.json
- views/prisonerProfile/prisonerVisits/prisonerVisits.njk
> NN-2460: ✨ Add visit start time and remove status

- backend/controllers/prisonerProfile/prisonerVisits.ts
- backend/routes/prisonerProfileRouter.ts
- integration-tests/integration/prisonerProfile/prisonerVisits.spec.js
- views/prisonerProfile/prisonerVisits/partials/prisonerVisitsSearchForm.njk
- views/prisonerProfile/prisonerVisits/prisonerVisits.njk
- SDI-4: ✨ Add additional visit fields
- SDI-4: ✨ Rename page and add different no data message
> SDI-4: rename page

- backend/controllers/homepage/homepage.ts
- backend/tests/homepageController.test.ts
> DCS-1381 change HDC card title and description

- integration-tests/integration/globalsearch/globalSearch.spec.js
- views/globalSearch/partials/globalSearchList.njk
> DCS-1482 change text of HDC link in global search

- src/Attendance/AttendanceOtherForm/AttendanceOtherForm.js
- src/Attendance/AttendanceOtherForm/AttendanceOtherForm.test.js
- SDI-125: 🐛 Reset sub reason if absence reason changed
- SDI-129: 🐛 Make case note display same as generated by whereabouts
> SDI-129: 🐛 Make case note display same as generated by whereabouts

- backend/api/incentivesApi.ts
- backend/api/prisonApi.ts
- backend/controllers/prisonerProfile/prisonerChangeIncentiveLevelDetails.ts
- backend/tests/prisonerChangeIncentiveLevelDetails.test.ts
- integration-tests/mockApis/incentivesApi.js
- integration-tests/mockApis/prisonApi.js
- integration-tests/plugins/index.js
https://dsdmoj.atlassian.net/browse/INC-292
> INC-292: call Incentives API when adding new IEP entry

- src/IncentiveLevelCreated/IncentiveLevelCreated.js
- src/IncentiveLevelCreated/IncentiveLevelCreated.test.js
> SDI-53: 💄 New design for iep slip

- integration-tests/integration/activity/activityList.spec.js
- integration-tests/integration/activity/houseblockList.spec.js
- src/Attendance/AttendanceOptions/AttendanceOptions.js
- src/Attendance/AttendanceOptions/AttendanceOptions.test.js
Reverts ministryofjustice/digital-prison-services#2080
> Revert "SDI-53: 💄 Add added on iep warning links"

- backend/controllers/attendance/activityList.ts
- backend/controllers/attendance/attendance.ts
- backend/controllers/attendance/houseblockList.ts
- backend/mappers.ts
- backend/tests/activityList.test.ts
- backend/tests/attendance.test.ts
- backend/tests/houseblockList.test.ts
- integration-tests/integration/activity/activityList.spec.js
- integration-tests/integration/activity/houseblockList.spec.js
- integration-tests/mockApis/responses/absenceReasonsV2.json
This reverts commit 22f49f9647e1ab8bb11628f9f651d5d10f5cf60e.
> Revert "SDI-53: ✨ Use descriptions from backend (#2075)"

- backend/api/incentivesApi.ts
- backend/controllers/prisonerProfile/prisonerChangeIncentiveLevelDetails.ts
- backend/controllers/prisonerProfile/prisonerIncentiveLevelDetails.ts
- backend/controllers/prisonerProfile/prisonerQuickLook.ts
- backend/tests/prisonerChangeIncentiveLevelDetails.test.ts
- backend/tests/prisonerIncentiveLevelDetails.test.ts
- backend/tests/prisonerQuickLook.test.ts
- integration-tests/mockApis/incentivesApi.js
https://dsdmoj.atlassian.net/browse/INC-293
> INC-293: pass with-details flag to Incentives API

- backend/api/incentivesApi.ts
- backend/api/prisonApi.ts
- backend/routes.ts
- backend/routes/establishmentRollRouter.ts
- backend/routes/prisonerProfileRouter.ts
- backend/services/movementsService.ts
- backend/services/prisonerProfileService.ts
- backend/tests/movementsService.test.ts
- backend/tests/prisonerProfileService.test.ts
- integration-tests/integration/establishmentRollCount/currentlyOut.spec.js
- integration-tests/integration/establishmentRollCount/enRoute.spec.js
- integration-tests/integration/establishmentRollCount/inReception.spec.js
- integration-tests/integration/establishmentRollCount/inToday.spec.js
- integration-tests/integration/establishmentRollCount/outToday.spec.js
- integration-tests/integration/establishmentRollCount/totalOut.spec.js
- integration-tests/mockApis/incentivesApi.js
- integration-tests/mockApis/prisonApi.js
- integration-tests/plugins/index.js
https://dsdmoj.atlassian.net/browse/INC-461
> INC-461: call Incentives API to get IEP summaries for a list of prisoners

- backend/controllers/search/prisonerSearch.ts
- backend/routes.ts
- backend/routes/prisonerSearchRouter.ts
- backend/tests/prisonerSearch.test.ts
- integration-tests/integration/search/prisonerSearch.spec.js
https://dsdmoj.atlassian.net/browse/INC-470
> INC-470: call Incentives API to get IEP summaries when searching for prisoners

- integration-tests/integration/activity/activityList.spec.js
- integration-tests/integration/activity/houseblockList.spec.js
- src/Attendance/AttendanceOptions/AttendanceOptions.js
- src/Attendance/AttendanceOptions/AttendanceOptions.test.js
This reverts commit 93e9ee6d2c15670c8eff5fdce38e8ca13ed44b20.
There were conflicts with automatic revert so had to do it on the command line.
> Revert "Revert "SDI-53: 💄 Add added on iep warning links (#2080)" (#2084)"

- backend/controllers/attendance/activityList.ts
- backend/controllers/attendance/attendance.ts
- backend/controllers/attendance/houseblockList.ts
- backend/mappers.ts
- backend/tests/activityList.test.ts
- backend/tests/attendance.test.ts
- backend/tests/houseblockList.test.ts
- integration-tests/integration/activity/activityList.spec.js
- integration-tests/integration/activity/houseblockList.spec.js
- integration-tests/mockApis/responses/absenceReasonsV2.json
This reverts commit b5050ea5ead98f3a88e0be72a1650802cd4d7506.
> Revert "Revert "SDI-53: ✨ Use descriptions from backend (#2075)" (#2086)"

- backend/api/curious/types/Enums.ts
- backend/routes/prisonerProfileRouter.ts
- backend/services/prisonerProfileService.ts
- backend/tests/prisonerProfileService.test.ts
- integration-tests/integration/alerts/createAlert.spec.js
- integration-tests/integration/caseNotes/case-note-amendments.spec.js
- integration-tests/integration/caseNotes/createCaseNote.spec.js
- integration-tests/integration/prisonerProfile/caseNotesPage.spec.js
- integration-tests/integration/prisonerProfile/employabilitySkillsDetails.spec.js
- integration-tests/integration/prisonerProfile/prisonerAlertsPage.spec.js
- integration-tests/integration/prisonerProfile/prisonerQuickLook.spec.js
- integration-tests/integration/prisonerProfile/prisonerSentenceAndRelease.spec.js
- integration-tests/integration/prisonerProfile/prisonerWorkAndSkills.spec.js
- integration-tests/integration/search/prisonerSearch.spec.js
- integration-tests/mockApis/dataCompliance.js
- integration-tests/pages/prisonerProfile/prisonerAlertsPage.js
- views/prisonerProfile/partials/prisonerProfileHeader.njk
Reverts ministryofjustice/digital-prison-services#2096
> Revert "Eswe 93 neurodiversity indicator"

- backend/controllers/search/prisonerSearch.ts
- backend/routes.ts
- backend/routes/prisonerSearchRouter.ts
- backend/tests/prisonerSearch.test.ts
- integration-tests/integration/search/prisonerSearch.spec.js
https://dsdmoj.atlassian.net/browse/INC-470
> Revert "INC-470: call Incentives API to get IEP summaries when searching for prisoners (#2094)"

- backend/api/incentivesApi.ts
- backend/api/prisonApi.ts
- backend/routes.ts
- backend/routes/establishmentRollRouter.ts
- backend/routes/prisonerProfileRouter.ts
- backend/services/movementsService.ts
- backend/services/prisonerProfileService.ts
- backend/tests/movementsService.test.ts
- backend/tests/prisonerProfileService.test.ts
- integration-tests/integration/establishmentRollCount/currentlyOut.spec.js
- integration-tests/integration/establishmentRollCount/enRoute.spec.js
- integration-tests/integration/establishmentRollCount/inReception.spec.js
- integration-tests/integration/establishmentRollCount/inToday.spec.js
- integration-tests/integration/establishmentRollCount/outToday.spec.js
- integration-tests/integration/establishmentRollCount/totalOut.spec.js
- integration-tests/mockApis/incentivesApi.js
- integration-tests/mockApis/prisonApi.js
- integration-tests/plugins/index.js
https://dsdmoj.atlassian.net/browse/INC-461
> Revert "INC-461: call Incentives API to get IEP summaries for a list of prisoners (#2092)"

- src/Attendance/AttendanceOtherForm/AttendanceOtherForm.styles.js
Align the conditional block with the middle of the radio like in https://design-system.service.gov.uk/components/radios/#conditionally-revealing-a-related-question
> SDI-53: 💄 Sort out alignment

- sass/application.scss
- sass/components/_attendance-stats.scss
- views/attendanceStatistics.njk
> SDI-126: 💄 Line up stats to be same height

- backend/config.ts
Signed-off-by: mjwillis <michael.willis@digital.justice.gov.uk>
> HAAR-403 Change timeout/retry to 30/10

- .circleci/config.yml
- Dockerfile
- backend/index.ts
- package.json
Reverts ministryofjustice/digital-prison-services#2140
> NN-4019: Node 16 with uncaught exception handler

- backend/api/oauthApi.ts
- backend/api/systemOauthClient.test.ts
- backend/api/systemOauthClient.ts
- backend/index.ts
- backend/middleware/requestLimiter.ts
- backend/setupWebSession.ts
- integration-tests/mockApis/auth.js
- package-lock.json
- package.json
> NN-4114: Caching of auth client credentials (again)

- backend/index.ts
- backend/routes.ts
Reverts ministryofjustice/digital-prison-services#2147
> Revert "NN-4019: Add catch wrapper for probation docs"

- backend/config.ts
- helm_deploy/digital-prison-services/templates/_envs.tpl
Needed for Book a Video Link app
Test email addresses for dev & pre plus actual email address for prod, added to secrets
> DCS-1625 add OMU email address for HMP Norwich

- backend/api/whereaboutsApi.ts
- integration-tests/mockApis/whereabouts.js
Reverts ministryofjustice/digital-prison-services#2181
> Revert "SDI-214: ✨ Try out absences for reason new endpoint"

- backend/sessionManagementRoutes.ts
- integration-tests/integration/globalsearch/globalSearch.spec.js
- package-lock.json
- package.json
- NN-4208: Upgrade passport to 0.6
- NN-4207: Lint fixes
- NN-4207: 🐛 Fix for req.logout now being asynchronous
> NN-4207: Upgrade passport to 0.6

- views/addAppointment/addAppointment.njk
- views/alerts/createAlertForm.njk
- views/amendCaseNote.njk
- views/appointmentConfirmDeletion.njk
- views/appointmentDeleteRecurringBookings.njk
- views/appointmentDetails.njk
- views/caseNoteDeleteConfirm.njk
- views/caseNotes/addCaseNoteForm.njk
Signed-off-by: mjwillis <michael.willis@digital.justice.gov.uk>
> HAAR-500 Add prevent double click on add appointments, and case notes

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
enabled for Welcome people into prison
> DCS-1695 enabled HMP Exeter

- backend/config.ts
- backend/controllers/search/prisonerSearch.ts
- integration-tests/integration/search/prisonerSearch.cy.js
- views/prisonerSearch/partials/prisonerSearchForm.njk
> SDI-311 Search feature now sticky and env driven

- backend/controllers/homepage/homepage.ts
- backend/tests/homepageController.test.ts
Update the DPS tile for Legacy prison visits booking system. 
Change heading and description and updated tests
> vb-1216, update legacy tile in dps

- backend/controllers/homepage/homepage.ts
- backend/tests/homepageController.test.ts
> MPC tile on homepage reworded

- backend/api/incentivesApi.ts
- backend/controllers/prisonerProfile/prisonerChangeIncentiveLevelDetails.ts
- backend/controllers/prisonerProfile/prisonerIncentiveLevelDetails.ts
- backend/controllers/prisonerProfile/prisonerQuickLook.ts
- backend/tests/prisonerChangeIncentiveLevelDetails.test.ts
- backend/tests/prisonerIncentiveLevelDetails.test.ts
- backend/tests/prisonerQuickLook.test.ts
- integration-tests/integration/prisonerProfile/prisonerChangeIncentiveLevelDetails.cy.js
- integration-tests/integration/prisonerProfile/prisonerIncentiveLevelDetails.cy.js
- integration-tests/integration/prisonerProfile/prisonerQuickLook.cy.js
- views/prisonerProfile/prisonerChangeIncentiveLevelConfirmation.njk
…instead of calculating in DPS.
Shown on these pages: INC-798, INC-799, INC-800
> INC-779: Get next incentive review date from incentives api

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
> SDI-311 Turn on elatsic search for establishment search

- helm_deploy/values-prod.yaml
https://dsdmoj.atlassian.net/browse/NN-4650
> NN-4650: remove old SSCL IP

- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
Reverts ministryofjustice/digital-prison-services#2323
> Revert "NN-4738: Add Adjudications for NHI"

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
See also: https://github.com/ministryofjustice/hmpps-incentives-ui/pull/361
Should be deployed by 7 Jan.
> INC-953: Enable case note entry interruption for private beta prison group 3 of ‘Manage Incentives’

- views/maintenancePage.njk
https://dsdmoj.atlassian.net/browse/NN-4479
> NN-4479: update maintenance window

- renovate.json
https://dsdmoj.atlassian.net/browse/NN-4858
> NN-4858: drop docker config as project will be done manually

- backend/controllers/prisonerProfile/prisonerQuickLook.ts
- backend/tests/prisonerQuickLook.test.ts
- views/prisonerProfile/prisonerChangeIncentiveLevelConfirmation.njk
- views/prisonerProfile/prisonerIncentiveLevelDetails.njk
Relates to [hmpps-incentives-ui#417](https://github.com/ministryofjustice/hmpps-incentives-ui/pull/417)
> INC-1123: Indicate that reviews should be performed by a particular date not on it

- backend/config.ts
- backend/services/prisonerProfileService.ts
- backend/tests/prisonerProfileService.test.ts
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- views/prisonerProfile/partials/prisonerProfileHeader.njk
Adding a link into the warrant folder service. This will only appear if users have the digital warrant folder role, which has not been given to any real world users.
> MDWFP-92 Adding warrant folder button.

- backend/controllers/prisonerProfile/prisonerCaseNotes.ts
- backend/tests/caseNotesController.test.ts
- cypress.config.js
- integration-tests/integration/prisonerProfile/caseNotesPage.cy.js
https://dsdmoj.atlassian.net/browse/NN-4988
> NN-4988: disable access to offenderId/case-notes if user does not have access to caseload

- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
> NN-5004 enable sudbury 

- backend/azure-appinsights.ts
- backend/tests/azure-appinsights.test.ts
- package-lock.json
- package.json
https://dsdmoj.atlassian.net/browse/NN-5072
Copied/adapted from https://github.com/ministryofjustice/hmpps-incentives-ui/pull/466
> NN-5072: add user to request in App insights

- backend/azure-appinsights.ts
https://dsdmoj.atlassian.net/browse/NN-5072
Previous PR https://github.com/ministryofjustice/digital-prison-services/pull/2434
> NN-5072: missed including addTelemetryProcessor(addUserDataToRequests) from previous PR

- backend/azure-appinsights.ts
- backend/middleware/currentUser.test.ts
- backend/middleware/currentUser.ts
- backend/tests/azure-appinsights.test.ts
https://dsdmoj.atlassian.net/browse/NN-5072
> NN-5072: store username in res.locals.user and correctly retrieve activeCaseLoad

- backend/controllers/homepage/homepage.ts
- backend/tests/homepageController.test.ts
- integration-tests/integration/homepage/homepage.cy.js
- integration-tests/integration/prisonerProfile/prisonerIncentiveLevelDetails.cy.js
Planned release  **2nd of May**
Update WPIP tile on landing page in line with body scan release
> DCS-1594-update WPIP tile on DPS landing page

- backend/api/nonAssociationsApi.ts
- backend/controllers/cellMove/cellMoveUtils.ts
- backend/controllers/cellMove/searchForCell.ts
- backend/controllers/cellMove/selectCell.ts
- backend/controllers/cellMove/viewNonAssociations.ts
> NON-88 Update contract

- backend/api/prisonApi.ts
- backend/controllers/cellMove/considerRisks.ts
- backend/controllers/cellMove/selectReception.ts
- backend/routes/cellMoveRouter.ts
- backend/tests/cellMove/considerRisks.test.ts
- backend/tests/cellMove/selectReception.test.ts
- views/cellMove/selectReception.njk
new view and controller created to enable movement of prisoners to reception. The page is not accessible in the current flow but can be accessed by directly entering the url  (/cell-move/select-reception).
The /cell-move/select-cell page was used as a basis for the new page and the exact content isn't known yet as it is work in progress. Bare-bones tests added.
> MAP-163 new view for reception areas

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
Added to preprod and dev for showing NA from NA API on profile page and linking to new pages.
The prisons are:
- Full Sutton (Cat A/B, new prisoner profile)
- ISIS (YOI, current prisoner profile)
- Lowdham Grange  (Private, Cat B, current prisoner profile)
- Risley (Cat C, new prisoner profile)
> NON-237 Add LGI,FNI,ISI,RSI

- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
This will show the link to the non-associations service for the first, "technical test" prison (ISI).
A separate PR will enable the non-associations link also for the other
3 private beta prisons (FNI,LGI,RSI)
**NOTE**: This cannot be merged/released until we go live in these private beta prisons. We'll leave it as a draft PR for the time being.
> NON-261: non-associations private beta - Part 1

- backend/controllers/prisonerProfile/prisonerLocationHistory.ts
- backend/routes/prisonerProfileRouter.ts
- backend/tests/prisonerCellHistory.test.ts
- backend/tests/prisonerLocationHistory.test.ts
call prison-api cell endpoint with system token
> SDIT-1239 CellResource

- backend/controllers/receptionMove/confirmation.ts
- backend/routes/receptionMoveRouter.ts
- backend/tests/receptionMove/confirmation.test.ts
- views/partials/layout.njk
- views/receptionMoves/confirmation.njk
> MAP-291 Add reception move confirmation screen

- backend/controllers/establishmentRoll/noCellAllocated.ts
- backend/tests/establishmentRoll/noCellAllocated.test.ts
> SDIT-1242 LocationResource

- backend/controllers/homepage/homepage.ts
Note that the service calls itself _Check my diary_ so we are now consistent
> SDIT-1253: 💄 Fix capitalisation for check my diary

- backend/controllers/establishmentRoll/dashboard.ts
- backend/controllers/establishmentRoll/enRoute.ts
- backend/routes/establishmentRollRouter.ts
- backend/services/movementsService.ts
- backend/tests/establishmentRoll/dashboard.test.ts
- backend/tests/establishmentRoll/enRoute.test.ts
- backend/tests/movementsService.test.ts
Switch prison-api endpoints to use system client token
> SDIT-1257 MovementResource

- backend/services/existingEventsService.ts
- backend/tests/existingEventsService.test.ts
> SDIT-1261 ScheduleResource

- backend/controllers/prisonerProfile/prisonerPersonal.ts
- backend/controllers/prisonerProfile/prisonerProfessionalContacts.ts
- backend/tests/prisonerPersonal.test.ts
switch /persons prison-api calls to system client
> SDIT-1313 PersonResource

- backend/controllers/changeCaseload.ts
- backend/controllers/establishmentRoll/noCellAllocated.ts
- backend/index.ts
- backend/middleware/currentUser.test.ts
- backend/middleware/currentUser.ts
- backend/routes.ts
- backend/routes/attendanceChangesRouter.ts
- backend/routes/changeCaseloadRouter.ts
- backend/tests/attendanceChanges.test.ts
- backend/tests/changeCaseload.test.ts
- backend/tests/establishmentRoll/noCellAllocated.test.ts
- integration-tests/integration/prisonerProfile/prisonerPrivateCash.cy.js
- integration-tests/integration/prisonerProfile/prisonerSavings.cy.js
- integration-tests/integration/prisonerProfile/prisonerSpends.cy.js
- src/Attendance/AttendanceOptions/AttendanceOptions.test.js
switch some /users endpoints to client token
> SDIT-1410 UserResource

- backend/controllers/receptionMove/considerRisksReception.ts
- backend/services/movementsService.ts
- backend/tests/movementsService.test.ts
- backend/tests/receptionMove/considerRisksReceptionController.test.ts
This code fixes bugs identified in [MAP-664](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?selectedIssue=MAP-664)
[MAP-664]: https://dsdmoj.atlassian.net/browse/MAP-664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MAP-664 prevent additional api calls if no prisoners in reception

- backend/services/appointmentsService.ts
- backend/services/existingEventsService.ts
- backend/tests/appointmentsService.test.ts
- backend/tests/existingEventsService.test.ts
[MAP-1550](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?selectedIssue=MAP-1550)
Removed the following unused functions
`existingEventsService.getAvailableLocationsForVLB()` 
`appointmentsService.getAppintments()`, 
`appointmentsService.addAppointments()` 
`appointmentsService.getLocationAndAppointmentDescription()`
Appointments and events are now handled by the prisoner-profile service
[MAP-1550]: https://dsdmoj.atlassian.net/browse/MAP-1550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
>  MAP-1550 remove unused function and test

- views/whereaboutsServiceDeactivated.njk
> SAA-2029: Refactor no longer in service page
