.eslintrc, backend/api/oauthApi.js, backend/tests/api/oauthApi.test.js
See https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/
=> NN-1285 swapped new Buffer for Buffer.from

src/App.js, src/EstablishmentRoll/EstablishmentRollBlock.js, src/EstablishmentRoll/EstablishmentRollBlock.test.js, src/routePaths.js
Add 'link' style to establishmentroll clickable stats. 
Move map of statistics names to paths of details pages outside EstablishmentRollBlock and move export of constants to a separate file to fix circular imports problem.
=> NN-1441 'In today' results page

backend/controllers/movementsService.js, backend/tests/movementsService.test.js, prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/mockapis/Elite2Api.groovy, src/EstablishmentRoll/EstablishmentRollBlock.js
- Remove link from establishment roll page when the result count is zero
- Return all recent movements regardless of movement type
=> NN-1553 in reception results page fixes

.circleci/config.yml
Currently get a warning in the docker build saying: 
```
[Warning] One or more build-args [CLIENT] were not consumed
```
e.g: https://circleci.com/gh/ministryofjustice/prisonstaffhub/3010
=> Remove unused variable

src/Adjudications/AdjudicationHistory/AdjudicationHistoryForm.js, src/Adjudications/AdjudicationHistory/__snapshots__/AdjudicationHistoryForm.test.js.snap
This previously only appeared on the first load and was then not selectable after another option was chosen,
meaing that the user had to 'clear filters' to reset it.
=> NN-1632 Adding All option to select box.

prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/IepHistory.groovy, prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/IepHistorySpecification.groovy, src/Adjudications/AdjudicationHistory/__snapshots__/AdjudicationHistoryForm.test.js.snap, src/Components/FilterForm/FilterForm.styles.js, src/IepHistory/IepHistory.js, src/IepHistory/IepHistoryContainer.js, src/IepHistory/IepHistoryForm.js, src/IepHistory/__snapshots__/IepHistory.test.js.snap, src/IepHistory/__snapshots__/IepHistoryForm.test.js.snap, src/routePaths.js, src/routes.js
Minor interface tweaks to IEP details page:
1. Change `IEP history/level` to `IEP details` in page heading, breadcrumbs and urls.
2. Fiddle with padding on form to reduce empty grey space.
3. User lighter grey colour for form background to match other filter forms on Quick Look such as Case Notes.
4. Increase size of `IEP history` heading
5. Enable `All` option in filters
=> Nn 1921 update filters and display

prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/AgencySelectionSpecification.groovy, src/App.js
Currently both of the above pages redirect to wherearebouts home,
which is not the where the user got to them. This updates the switchCaseload
logic to detect pages under the 'offenders' path and to redirect those
to the notm interface instead.
=> NN-1927: Update case switching for IEP details and Adjudications

backend/config.js, backend/controllers/getConfig.js, package.json, src/App.js, src/flags.js, src/index.js, src/redux/reducers/index.js, yarn.lock
Adding [garbles/flag](https://github.com/garbles/flag) to allow managing and implementing feature flags.
Flags registered in `backend/config.js` like: 
```js
app: {
featureFlags: { 
myFlagName: process.env.MY_FLAG_NAME === 'true' 
}
}
```
Will then be available to `Flag`s in react components:
```js
<Flag
name={['myFlagName']}
render={() => (
<span>Feature Enabled</span>
)}
fallbackRender={() => (
<span>Feature Disabled</span>
)}
/>
```
=> NN-1677 Adding garbles/flag to add support for adding feature flags

backend/controllers/activityList.js, backend/tests/activityList.test.js, src/ResultsActivity/ResultsActivity.js, src/ResultsActivity/ResultsActivityContainer.js, src/ResultsActivity/elements/PayOptions/PayOptions.js, src/ResultsActivity/elements/PayOptions/PayOptions.test.js
Replace the current logic for hiding Pay/Other with a check for whether the attendance is locked. Display the Pay/Other column headings regardless as different rows could have different displays (some attendances become locked before others). Hide radio buttons if the attendance is locked.
=> Nn 2012 use locked property for radio button logic

src/IepDetails/IepChangeContainer.js, src/IepDetails/IepChangeGaEvents.js, src/IepDetails/IepChangeGaEvents.test.js
Previously the GA events included the new IEP level and the reason
for the change. We determined the reason was not necessary and should be
replaced by the offender's previous level and the agency where
the change was made.
=> NN-1961: Update GA events

src/ResultsActivity/elements/PayOtherForm/PayOtherForm.js, src/ResultsActivity/elements/PayOtherForm/PayOtherForm.test.js
The limit of 240 applies to both event outcomes and IEP warnings.
=> NN-2074 add client side validation on comments

prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/HouseblockSpecification.groovy, src/ResultsActivity/elements/PayOptions/PayOptions.js
For https://dsdmoj.atlassian.net/browse/NN-2059
This adds a bit more complexity in what we show on the houseblock lists. Unlike the activity lists, the absence reason here is not a link so is not editable. Also, if we have no attendance data for a locked record, we should 'Not Recorded'.
=> Nn 2059 houseblock list attendance values

backend/controllers/iepDetails.js, backend/tests/iepDetails.test.js
For https://dsdmoj.atlassian.net/browse/NN-2103
We allowed them Entry before because it supported a few weird workflows. Estate policy is changing to not allow Entry to be set anymore, so we shouldn't show it on the Change IEP page.
=> NN-2103: Remove Entry from possible options for Change IEP

src/ResultsActivity/ResultsActivity.js, src/ResultsActivity/ResultsActivity.test.js
This change checks the unpaid offenders list for any offenders with 'other' attendance information already selected and updates the attend all button to say 'pay remaining...' instead of 'pay all...'
=> NN-2113 updated attendance button where other attend info exists

src/ResultsActivity/ResultsActivity.js
Fixes an issue where if there is no eventId and there are multiple rows for the same offender, the key is `offenderNo-undefined` which causes only 1 of the rows to be removed and the others to remain when content new lists are rendered. 
From what I can see, there's no other unique item to use and it appears to be that the missing `eventId` is likely to be only a dev data issue anyway, so `index` is our only option as the fallback, despite it being considered an anti-pattern.
=> NN-2139 - Fix duplicate row in activity list if there is no eventId

src/ResultsActivity/ResultsActivity.js, src/ResultsActivity/ResultsActivity.test.js
When attending all/remaining prisoners, we are doing two loops - one loop which goes over all the offenders in the API response and calls the reducer, and then within the reducer another loop which loops over all of the offenders in state until it finds a match. When users are using the attend all functionality on pages with a lot of offenders (300), they are getting a 'something is making your browser slow' error due to the large amount of client-side processing.
Since this functionality is used on a large group of offenders at once, instead of updating state one by one, this PR proposes we simply refresh the activity list same way the page is loaded in the first place. As the attendances have been updated already through the batch API call, the returned data is equivalent to if we …
=> NN-2121: Refresh page instead of updating state

src/ResultsActivity/ResultsActivity.js, src/ResultsActivity/ResultsActivity.test.js, src/ResultsActivity/ResultsActivityContainer.js, src/redux/reducers/index.js, src/redux/reducers/reducers.test.js
For https://dsdmoj.atlassian.net/browse/NN-2109
This changes the 'Prisoners paid' label on the activity list to now say 'Sessions attended'. It also changes what this session represents from all paid activities to all paid activities without an absence reason, so all who attended.
It also changes what the 'Prisoners listed' label represents, from a count of all main activities on the page to a count of all the unique prisoners.
=> Nn 2109 update labels activity list

backend/utils.js, backend/utils.test.js, backend/utils/nunjucksSetup.js, package.json, src/App.test.js, src/dateHelpers.js
- Add nunjucks filters for getting date and time from string
- Removed `testMatch` from package.json as defaults suffice see https://jestjs.io/docs/en/configuration#testmatch-array-string
- Remove unnecessary async from describe in App.test.js
- Exported dateHelpers to use in node
=> NN-2173 Add nunjucks filters for getting date and time from string

prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/mockapis/Elite2Api.groovy, prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/mockapis/mockResponses/ActivityResponse.groovy, prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/pages/ActivityPage.groovy, prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/ActivitySpecification.groovy, src/Components/ResultsTable/elements/TotalResults/TotalResults.js, src/Components/ResultsTable/elements/TotalResults/__snapshots__/TotalResults.test.js.snap, src/ResultsActivity/ResultsActivity.js
The totalOffenders variable was initiated once set on the
component at first render. There was no point at which that
variable was reset when the component updated, thus it sometimes
showed wrong results when the period was changed.
This adds an integration test to confirm correct behaviour.
=> Nn 2199 fix prisoners listed number bug

src/ResultsActivity/ResultsActivity.js, src/ResultsActivity/ResultsActivity.test.js
Currently the batch actions will send all unattended activities on the pages, regardless if they have an eventId or not. We don't show the radio buttons when there's no eventId, but we didn't have a similar check for batch actions. This also updates the showing of the action buttons logic to only show them if there are updatable offenders remaining (checks for eventId again).
=> NN-2206: Check activity has eventId before including it in batch actions

prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/HouseblockSpecification.groovy
Temporarily remove flaky test that is failing due to the interactive nature of the page and the way the spinner works. 
The test covers the behaviour of the house block page automatically refreshing when either the location or date has changed. Each time either elements are updated the spinner gets triggered several times, showing, hiding and showing etc.
Some effort is required to fix the page or come up with a clever way to determine if the page has been refreshed. 
The longer-term goal is to convert this page to server side tech.
=> Temporarily remove flaky test.

backend/controllers/attendanceStatistics.js, backend/tests/attendanceStatistics.test.js, views/attendanceStatisticsOffendersList.njk
Previous we were returning the first event, which wasn't necessarily the one the absence was for. This resolves and updates the page heading.
=> NN-2030: Make sure correct event is shown for absence, update page heading

backend/controllers/probationDocuments.js, backend/tests/probationDocuments.test.js
Fix a scenario (unlikely to happen in live) where no documents have ever been uploaded for any conviction ever
=> DT-343 fixed issue when offender has no sentence related documents

backend/controllers/activityList.js, backend/tests/activityList.test.js
Someway somehow (probably JS async issue) sometimes users manage to make a request where the locationId is '--'. Currently this is being passed onto the APIs, this is to catch that error and stop the process before it gets to elite2.
=> NN-1902: Add error handling if the locationId is missing

backend/controllers/bulkAppointmentsClashes.js, backend/controllers/bulkAppointmentsConfirm.js, backend/raiseAnalyticsEvent.js, backend/tests/bulkAppointmentsClashes.test.js, backend/tests/bulkAppointmentsConfirm.test.js
Add value parameter so we can remove the number of people paid/appointments created from the Event action name and make the figures easier to collate.
=> NN-2252/NN-2253 Add value parameter to raiseAnalyticsEvent

package.json, yarn.lock
Update new-nomis-shared and a vulnerability in the serialize-javascript package.
=> NN-2337: Update new-nomis-shared and fix security vulnerability

static/js/main.js
Remove `console.log` in main.js which was causing none of the JS in that file to run in IE11 because of es2015 syntax.
=> NN-2288 Remove rogue console log which triggered error in IE11

backend/shared/getExternalEventsForOffenders.js, backend/tests/getExternalEventsForOffenders.test.js, backend/utils.js
Do not show the following on lists when the selected date is in the future.
- Scheduled transfers
- Court events
- Release information
=> NN-2401 Prevent some external movements being shown on future lists

backend/api/elite2Api.js, backend/api/whereaboutsApi.js, backend/controllers/attendance/houseblockList.js, backend/tests/houseblockList.test.js, prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/mockapis/Elite2Api.groovy, prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/mockapis/WhereaboutsApi.groovy, prisonstaffhub-specs/src/test/groovy/uk/gov/justice/digital/hmpps/prisonstaffhub/specs/HouseblockSpecification.groovy
As part of the move of location group property files from elite2 to whereabouts, any requests to retrieve location groups must be made to whereabouts.  
This means that we have changed the elite2 endpoint used by getHouseblockList to receive a list of location ids as input instead of deriving the locations by itself - it can't derive locations as it doesn't know about the location group property files anymore.
=> DT-526 schedule groups retrieved from whereabouts

backend/tests/houseblockList.test.js
The test data is not actually relevant to the test but it seems best
not to confuse people with incorrect test data.
=> DT-526 Fix test data

backend/controllers/appointments/viewAppointmentsController.js, backend/tests/viewAppointmentsController.test.js
When there's no period specified, default to the period the current time is in.
=> NN-2387 view the current period by default

package.json, src/Components/RadioGroup/__snapshots__/RadioGroup.test.js.snap, yarn.lock
Also ran `yarn-deduplicate` on `yarn.lock`.  Consolidated some package versions which is the reason for the change of classNames in the snapshots.
=> NN-2491 Upgrade webpack to fix acorn vulnerability

backend/api/elite2Api.js, backend/controllers/prisonerProfile/prisonerQuickLook.js, backend/services/prisonerProfileService.js, backend/shared/filterActivitiesByPeriod.js, backend/tests/prisonerQuickLook.test.js
Still load the new prisoner profile quick look page if there's an error retrieving any of the information.  At the moment it will just display `--` for that piece of information. Specific errors to be handled by **NN-2463**
=> NN-2457 Handle api errors so quick look still loads

backend/index.js, backend/middleware/currentUser.js, backend/middleware/currentUser.test.js, backend/routes.js, views/partials/header.njk
- Use res locals to store the user data because it has a request lifecycle.
=> NN-2647 use res locals to store user data

backend/shared/alertFlagValues.js, src/FullFlags/fullFlags.scss
This rendered them in black and white:
Also fixed padding on attendance screen:
was:
<kbd><img width="190" alt="Screenshot 2020-06-08 at 10 13 30" src="https://user-images.githubusercontent.com/1517745/84013541-f6301900-a970-11ea-9778-934475b2391b.png"></kbd>
now: 
<kbd>
(typically only one alert of this type would be shown)
=> DCS-522 adding missing styles to new prisoner page

.circleci/config.yml, backend/controllers/covid/protectiveIsolationUnitController.js, backend/controllers/covid/reverseCohortingUnit.js, backend/controllers/covid/shieldingUnitController.js, backend/routes.js, backend/routes/covidRouter.js, backend/tests/protectiveIsolationUnitController.test.js, backend/tests/reverseCohortingUnitController.test.js, backend/tests/shieldingUnitController.test.js, integration-tests/integration/covid/view-dashboard.spec.js, integration-tests/pages/covid/dashboardPage.js, integration-tests/pages/covid/protectiveIsolationUnitPage.js, integration-tests/pages/covid/reverseCohortingUnitPage.js, integration-tests/pages/covid/shieldingUnitPage.js, views/covid/dashboard.njk
The numbers will only become links if there is at least one case.
Also moving all list page urls to a prefix of `/current-covid-units/`
(The dashboard which is currently on `/current-covid-units` will still be accessible on the original url so
the new-nomis url doesn't need to be updated)
=> DCS-527 Hooking up covid unit pages to dashboard

sass/_govuk-overrides.scss, sass/components/covid/dashboard.scss
Inserted CSS specifically for this element because there wasn't an option in the govuk warning component to target just the icon. Classes could be added to the component but only for the warning text not the icon.
=> DCS-539: warning icon made round using CSS

views/covid/dashboard.njk
Before:
<kbd>
</kbd>
After:
<kbd>
</kbd>
=> DCS-535 Fixing the highlighting on the covid dashboard links

backend/controllers/search/prisonerSearch.js, backend/tests/prisonerSearch.test.js
- Fix bug where a checked **ACCT open** `HA` would check both **ACCT Open** `HA` and **ACCT post closure** `HA1` on refresh but only search for **ACCT open** `HA`.
- Fix checkbox selection and API search bugs with checkboxes which have multiple associated alert codes. e.g. **Risk to LGBT** has codes `RTP` and `RLG`.
=> NN-2740 Fix new prisoner search alert checkbox combo bugs

backend/controllers/prisonerProfile/personalViewModels/activeContactsViewModel.js, backend/tests/prisonerPersonal.test.js
We only care about active addresses for a contact.  If there is an active address flagged as primary, show that, if not, show the most recently added active address.
=> NN-2757 Updated criteria for what active contacts get shown

backend/controllers/covid/covidDashboardController.js, backend/services/covidService.js, backend/tests/covidDashboardController.test.js, integration-tests/integration/covid/view-dashboard.spec.js, integration-tests/pages/covid/dashboardPage.js, sass/components/covid/dashboard.scss, views/covid/dashboard.njk, views/covid/macros.njk, views/covid/reverseCohortingUnit.njk
* Show a warning for newly arrived prisoners who do not have a COVID alert.
* Link the warning to the not-in-unit page.
=> DCS-573 COVID dashboard

views/editAlertForm.njk, views/prisonerProfile/prisonerQuickLook/partials/visits.njk
- Remove **View visit details** link on prisoner profile so we can release new prisoner profile pages.
- Also changed **re-activated** to **reactivated**
=> NN-2804 Remove visit details link temporarily

backend/controllers/prisonerProfile/prisonerQuickLook.js, backend/tests/prisonerQuickLook.test.js, views/macros/categoryFlag.njk, views/prisonerProfile/partials/prisonerProfileHeader.njk
The quicklook controller passed missing data values for some of the items in the header, while the rest of the controllers didn't. This resulted in a different missing value display depending on which tab you were on. This pulls the display logic entirely in the view by specifying the missing data value there and standardising controller behaviour.
=> NN-2806: Let views tackle missing data rather than controller

backend/controllers/search/prisonerSearch.js, backend/tests/prisonerSearch.test.js
Search results breaking when changing from list view to grid view because the alerts params were not an array.
=> NN-2381 Make alerts query param in search url an array

integration-tests/integration/covid/view-not-in-unit-list.spec.js, integration-tests/integration/covid/view-protective-isolation-list.spec.js, integration-tests/integration/covid/view-reverse-cohorting-list.spec.js, integration-tests/integration/covid/view-shielding-list.spec.js, views/covid/notInUnit.njk, views/covid/protectiveIsolationUnit.njk, views/covid/reverseCohortingUnit.njk, views/covid/shieldingUnit.njk
Dates were using shortened month names (Jan, Feb, ...)
Changed to use  full month name. For example 2 December 2020.
These changes affect date display in the Covid pages only.
=> DCS-582 COVID - Dates are in the incorrect format on the units

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
URL changes for manage-soc-services - updated to use the .hmpps.service.justice.gov.uk domain in all environments and set the enabled flags so that the links will show where the current user has a SOC role in their token.
=> PAT-1216: Updated URLs for SOC for altered domain name

backend/controllers/attendance/attendanceStatistics.js, backend/tests/attendanceStatistics.test.js, views/bulkAppointmentsAdded.njk, views/cellMove/offenderDetails.njk, views/confirmAppointments.njk, views/prisonerProfile/partials/prisonerProfileHeader.njk, views/prisonerProfile/prisonerCaseNotes/caseNotes.njk, views/prisonerProfile/prisonerCellHistory.njk, views/prisonerProfile/prisonerLocationHistory.njk, views/videolinkBookingConfirmHearingPrison.njk
The button is currently hidden so you can't see that the wrapping has changed. Below are screenshots of the wrapping before and after change with the button present for the same window size.
Also adding rel="noopener noreferer" to target="_blank" to follow best security practices.
=> Nn 2908 cell history tweaks

backend/controllers/cellMove/moveValidation.js, backend/tests/cellMove/moveValidation.test.js, views/cellMove/moveValidation.njk
Previously whether the category warning showed up was dependent on there being alerts, the two were wrongly tied together. This decouples the logic and ensures the category warning shows when the offender is cat A and there are other offenders in the cell.
=> Nn 2716 fix category warning

backend/controllers/cellMove/moveValidation.js, backend/tests/cellMove/moveValidation.test.js
Previously we were showing the LGB alert regardless of the sexualities involved, it was just the wording that changed. This updates it so that we only show the alert if there are non-straight sexualities involved, otherwise do not include the alert in the risks at all.
=> NN-2716: Update behaviour for LGB alert

backend/controllers/cellMove/selectCell.js, backend/tests/cellMove/selectCell.test.js
Sometimes a non-association's location with be 'OUTSIDE' which means they are no longer relevant to cell move, but also, that they don't have an assigned living unit. This PR handles that case.
=> NN-2933: Check assigned living unit exists

integration-tests/integration/dataCompliance/retentionReasons.spec.js, package-lock.json, package.json
Fixes security vulnerabilities reported by snyk. Upgrade cypress to avoid reliance on vulnerable lodash package.
=> NN-2932: Version upgrades to bunyan, ajv, lodash and cypress

backend/tests/attendanceStatistics.test.js
How this has worked at all is beyond me. JS magic.
=> NN-2932: Specify date format for query string so moment does not have to guess

integration-tests/integration/cellMove/selectCell.spec.js, integration-tests/pages/cellMove/selectCellPage.js, views/cellMove/selectCell.njk
Some tweaks to the Select cell page.
- Show message when there are no results
- Move cell swap link to top right (formerly bottom of table)
- Seperate cell types by comma and new line:
=> NN-2964 Update select cell page

integration-tests/integration/adjudicationHistory/adjudicationHistory.spec.js, integration-tests/integration/alerts/createAlert.spec.js, integration-tests/integration/alerts/editAlert.spec.js, integration-tests/integration/appointments/addAppointment.spec.js, integration-tests/integration/appointments/addBulkAppointments.spec.js, integration-tests/integration/appointments/addCourtAppointmentPrison.spec.js, integration-tests/integration/appointments/requestCourtBooking.spec.js, integration-tests/integration/appointments/viewAppointments.spec.js, integration-tests/integration/attendance/attendanceStatsPage.spec.js, integration-tests/integration/caseNotes/createCaseNote.spec.js, integration-tests/integration/cellMove/cellMoveConfirmation.spec.js, integration-tests/integration/cellMove/cellNotAvailable.spec.js, integration-tests/integration/cellMove/confirmCellMove.spec.js, integration-tests/integration/cellMove/cswapConfirmation.spec.js, integration-tests/integration/cellMove/moveValidation.spec.js, integration-tests/integration/cellMove/selectCell.spec.js, integration-tests/integration/cellMove/selectLocation.spec.js, integration-tests/integration/cellMove/viewCellSharingRiskAssessmentDetails.spec.js, integration-tests/integration/cellMove/viewNonAssociations.spec.js, integration-tests/integration/cellMove/viewOffenderDetails.spec.js, integration-tests/integration/dataCompliance/retentionReasons.spec.js, integration-tests/integration/establishmentRollCount/inReception.spec.js, integration-tests/integration/prisonerProfile/prisonerAlertsPage.spec.js, integration-tests/integration/prisonerProfile/prisonerPersonal.spec.js, integration-tests/integration/prisonerProfile/prisonerProfessionalContacts.spec.js, integration-tests/integration/prisonerProfile/prisonerSentenceAndRelease.spec.js, integration-tests/integration/search/prisonerSearch.spec.js, integration-tests/integration/videolink/courtVideoLinkBookingsPage.spec.js, integration-tests/integration/videolink/prisonerSearch.spec.js
We were calling the reset stubs task multiple times in some specs in close succession which contributed to some stubs not being found on login.
=> NN-2994: Reset stubbing only once per spec

backend/controllers/prisonerProfile/prisonerCellHistory.js, backend/tests/prisonerCellHistory.test.js, integration-tests/integration/prisonerProfile/prisonerCellHistory.spec.js
Cell movements are pre sorted in descending order before grouping, so the `fromDateString` and `toDateString` were the wrong way round.  Tests only had 1 record before so passed regardless. 😳 🙈 
Dates now correct as shown in screenshot below:
**From =** earliest move in date
**To =** latest move out date
=> NN-3033 Fix from and to dates on location history location titles

integration-tests/integration/prisonerProfile/prisonerQuickLook.spec.js, views/prisonerProfile/partials/prisonerProfileHeader.njk
Changed the wording in the service to 'Add' instead of Refer.
Also had to remove the async methods in the tests to appease the linter.
It's highlighted a failing test.
It seems we want the following error to show for the test
but instead get
This is toggled by line 196 in the ./backend/controllers/prisonersProfile/prisonerQuicklook.js
` personalDetailsSectionError: Boolean(prisonerDataResponse.error && prisonerProfileDataResponse.error),`
Can't seem to make out where prisonerProfileDataResponse.error is set so think the issue is around that?
Solutions:
- Make this an || operator (though I don't think prisonerProfileDataResponse.error is ever set, may just be me being blind)
- Remove prisonerProfileDataResponse.error from the check (though not sure if this is the desire functionality …
=> PAT-951: Update SOC referral button text

backend/api/caseNotesApi.js, backend/api/oauthEnabledClient.js, backend/controllers/deleteCaseNote.js, backend/controllers/prisonerProfile/prisonerCaseNotes.js, backend/routes.js, backend/routes/caseNoteDeletionRouter.js, backend/routes/prisonerProfileRouter.js, backend/tests/caseNotesController.test.js, backend/tests/deleteCaseNoteController.test.js, integration-tests/integration/prisonerProfile/caseNotesPage.spec.js, integration-tests/mockApis/caseNotes.js, integration-tests/pages/prisonerProfile/caseNotePage.js, integration-tests/plugins/index.js, views/caseNoteDeleteConfirm.njk, views/prisonerProfile/prisonerCaseNotes/caseNotes.njk
Secure case notes and amendments can be deleted if the user has the role `DELETE_SENSITIVE_CASE_NOTES`. No other users will see this functionality.
Initially this will be given to admins, to save people on call from having to delete them via API calls which is easy to get wrong.
=> DT-1078 Enable deleting secure casenotes

backend/index.js, backend/middleware/currentUser.js, backend/routes.js, backend/setupApiRoutes.js
Removing unnecessary session data clean and fixing issue where middleware called twice. 
Two routes on the same path will share any middleware added by `router.use`
=> DCS-759 Preventing middleware from being called twice

backend/controllers/homepage/homepage.js, backend/tests/homepageController.test.js, integration-tests/integration/homepage/homepage.spec.js, views/whereabouts/whereaboutsHomepage.njk
As they now appear on the new whereabouts homepage.
Also added card to pageScripts section of whereabouts homepage as I missed this from last PR.
=> NN-3154 Remove covid and bulk appointments link from DSP homepage

backend/controllers/selectActivityLocation.js, backend/tests/selectActivityLocationsController.test.js, views/error.njk
The select activity location page uses a very slow query that generally times out on the first few tries. This ticket stops these types of errors polluting our azure logs. 
Longer time we need to investigate if elastic search is a viable solution to this problem.
=> NN-3197 handle timeouts

backend/controllers/cellMove/confirmCellMove.js, backend/tests/cellMove/confirmCellMove.test.js, integration-tests/integration/cellMove/confirmCellMove.spec.js, integration-tests/pages/cellMove/confirmCellMovePage.js, views/cellMove/confirmCellMove.njk
Link text changed to cancel as there is now multiple entry points to this page. Returns to search for cell page by default, but should use the referring url, if available.
=> NN-3175 Update back/cancel link on confirm cell move page

backend/controllers/cellMove/considerRisks.js, backend/tests/cellMove/considerRisks.test.js, integration-tests/integration/cellMove/considerRisks.spec.js, integration-tests/pages/cellMove/considerRisksPage.js, views/cellMove/considerRisks.njk
When there are no inmates in the location you are moving a prisoner too (usually single occupancy):
- Do not display CSRA info
- Confirmation label should not mention any prisoner names and just say, **Are you sure you want to select this cell?**
=> NN-3149 Update content on cell move consider risks page

backend/controllers/cellMove/selectCell.js, backend/tests/cellMove/selectCell.test.js
Do not show temporary cell codes in select-cell - show the description
=> NN-3187: Do not show temporary cell names when selecting cell

backend/controllers/cellMove/confirmCellMove.js, backend/tests/cellMove/confirmCellMove.test.js, integration-tests/integration/cellMove/confirmCellMove.spec.js, views/cellMove/confirmCellMove.njk
=> NN-3238 Hide comment input on confirm move page when cswap/create space

package-lock.json
`y18n` is a dependancy of `jest` which we are on the latest version of (26.6.3).  I believe there's an update to the package in v27 when it comes out.
`npm audit` suggested running `npm update y18n --depth 9` and this PR is a result of that.
=> NN-3290 Upgrade dependency of jest to fix security audit

backend/controllers/cellMove/cellMoveHomepage.js, backend/controllers/whereabouts/whereaboutsHomepage.js, backend/routes.js, backend/tests/cellMoveHomepage.test.js, backend/tests/whereaboutsHomepage.test.js, integration-tests/integration/cellMove/cellMoveHomepage.spec.js, integration-tests/integration/whereabouts/whereaboutsHomepage.spec.js, views/cellMove/cellMoveHomepage.njk
Also removed a call to oAuth on the existing whereabouts homepage as none of the tasks are role dependant.
=> NN-3263 Add new cell move homepage

.eslintignore, audit-ci.json, package-lock.json, package.json
Added [1677](https://www.npmjs.com/advisories/1677) to allowlist however it is because of a dependancy of jest.  There's an issue raised on their github which I've subscribed to so will keep an eye on https://github.com/facebook/jest/issues/11383.
Also removed [961](https://www.npmjs.com/advisories/961) from allowlist as no longer an issue for us.
=> NN-3372 Fix current npm security audit issues

backend/api/whereaboutsApi.js, backend/controllers/appointments/prepostAppoinments.js, backend/tests/prepostAppointments.test.js, integration-tests/integration/appointments/addAppointment.spec.js, integration-tests/mockApis/whereabouts.js, integration-tests/plugins/index.js
We now send will send court ids when creating new bookings when we can tie this to a specific known court
We still will need to send the court name through if a user selects an 'other' court. These other courts won't appear in the BVL booking list
=> DCS-983 Send court ids when creating a BVL booking

backend/controllers/appointments/prepostAppoinments.js, backend/tests/prepostAppointments.test.js, integration-tests/integration/appointments/addAppointment.spec.js, integration-tests/pages/appointments/prePostAppointmentsPage.js, views/enterCustomCourt.njk, views/prepostAppointments.njk
Removing the ability to specify pre/post appointment duration - these will now always be 15 mins long instead.
=> DCS-1007 Prevent users from specifying duration of pre/post appointments 

backend/controllers/cellMove/cellMovePrisonerSearch.js, backend/controllers/cellMove/cellMoveTemporaryMove.js, backend/controllers/cellMove/cellMoveViewResidentialLocation.js, backend/tests/cellMove/cellMovePrisonerSearch.test.js, backend/tests/cellMove/cellMoveTemporaryMove.test.js, backend/tests/cellMove/cellMoveViewResidentialLocation.test.js, views/cellMove/cellMovePrisonerSearch.njk, views/cellMove/cellMoveTemporaryMove.njk, views/cellMove/cellMoveViewResidentialLocation.njk
I think the missing error messages at the location of the error was caused by a missing piece of code in the njk file, though the actual error message at that point wasn't recognised whilst it was using the 'html' key in the controller (used so that we could specify the correct apostrophe code), so I've swapped that out for the plain text version. I've checked the apostrophe and it matches the one we had previously.
=> NN-3383 fix error message format

backend/api/offenderSearchApi.js, backend/controllers/prisonerProfile/prisonerQuickLook.js, backend/controllers/prisonerProfile/prisonerSentenceAndRelease.js, backend/routes.js, backend/routes/prisonerProfileRouter.js, backend/tests/prisonerQuickLook.test.js, backend/tests/prisonerSentenceAndRelease.test.js, integration-tests/integration/prisonerProfile/prisonerSentenceAndRelease.spec.js, integration-tests/mockApis/offenderSearch.js, integration-tests/plugins/index.js
The original implementation was relying on a prison-api call to determine if the offender had a Life term, however that didnt quite work in all scenarios. It needed some extra derivation on the sentence terms - after a slack chat with other dps devs it turns out the prisoner search service does this derivation https://mojdt.slack.com/archives/C012FNNQ4A3/p1623854264294400
So changed it to call the elastic  prisoner-search-service which returns a flag which fits our purpose.
=> NN-3279 use offender search to determine if the prisoner has a life sentence term

backend/api/curious/curiousApi.test.ts, backend/api/curious/curiousApi.ts, backend/api/curious/types/AssessmentQualificationType.ts, backend/api/curious/types/LearnerEducationDeliveryMethodType.ts, backend/api/curious/types/index.d.ts, backend/controllers/prisonerProfile/prisonerWorkAndSkills.js, backend/routes/prisonerProfileRouter.js, backend/services/esweService.ts, backend/services/prisonerProfileService.js, backend/tests/esweService.test.ts, backend/tests/prisonerProfileService.test.js, views/prisonerProfile/macros/prisonerSummarySection.njk, views/prisonerProfile/partials/prisonerProfileTabs.njk, views/prisonerProfile/prisonerWorkAndSkills/partials/learnerLatestAssessments.njk, views/prisonerProfile/prisonerWorkAndSkills/prisonerWorkAndSkills.njk
This PR introduces a new tab to the prisoner profile views to start to display work and skills information.
The work is behind a feature flag and uses mock data. This PR will be followed up with the curious api integration.
=> NN-3481: implement functional skills levels

backend/api/curious/curiousApi.test.ts, backend/api/curious/curiousApi.ts, backend/services/esweService.ts, backend/tests/esweService.test.ts
This PR:
- Removes curious learner assessment mock data form the source code
- Gets offender specific learner assessment data from the curious api
=> NN-3500: gets learner assessment data from the curious api

backend/controllers/appointments/viewAppointments.js, backend/tests/viewAppointmentsController.test.js, views/viewAppointments.njk
When there was no associated pre or post appointments, the page wouldn't load.
Also hide the View details links and column from print.
=> NN-3485 Fix for when there is only a main vlb appointment

backend/controllers/controller.js, backend/tests/activityListController.test.js, src/ResultsActivity/ResultsActivityContainer.js
Eddie requested we give the user some indication that the request timed out - so I decided we give an obscure error message as shown below.
Secondly, I think we need to have some visibility on timeouts - surely it is important to know that things are not operating correctly, therefore I have added logging on timeout. I wasn't brave enough to report a 500 as it was deliberately removed as part of other tickets, e.g https://dsdmoj.atlassian.net/browse/NN-2878.
=> NN-3426: Handle activity list timeouts better

backend/setupApiRoutes.js, integration-tests/integration/activity/activityList.spec.js, integration-tests/integration/homepage/homepage.spec.js, src/Components/FeedbackBanner/FeedbackBanner.js, views/components/feedbackBanner/feedbackBanner.njk
Make it easier to distinguish between apps in the surveymonkey report, particularly when this will be on other services and there will be multiple  root `/` paths
=> NN-3482 Include hostname in survey monkey url source

backend/controllers/cellMove/cellMoveUtils.js, backend/controllers/cellMove/confirmCellMove.js, backend/tests/cellMove/confirmCellMove.test.js, integration-tests/integration/cellMove/confirmCellMove.spec.js, views/cellMove/confirmCellMove.njk
This PR updates the content of the back link button on the confirmCellMove view depending on what the last url to get there.
If you a simply selecting a cell then the button will say 'Cancel'. 
If you have came from searching for a sell the button will say 'Select another cell'.
=> NN-3252: Cell move - confirm move page - variable 'cancel' link change

backend/routes/prisonerProfileRouter.js, backend/services/esweService.ts, backend/tests/esweService.test.ts, integration-tests/integration/prisonerProfile/prisonerWorkAndSkills.spec.js, integration-tests/plugins/index.js, views/prisonerProfile/prisonerWorkAndSkills/partials/learnerLatestAssessments.njk, views/prisonerProfile/prisonerWorkAndSkills/prisonerWorkAndSkills.njk
This PR:
- refactors the esweService getLatestLearnerAssessments function, removing unnecessary sorting on the API results and removes replication
- renames error variables
- adapts to the new error response from megaNexus regarding a record not found
- includes a new unit test, and corrects dummy data used
- adapts integration test for when the prisoner is not in Curious
=> Nn 3548 refactor functional skills

backend/controllers/cellMove/cellMoveUtils.js, backend/tests/cellMove/confirmCellMove.test.js, integration-tests/integration/cellMove/confirmCellMove.spec.js
This PR: 
- shows 'Cancel' content on back link when going through the route prisoner profile > change cell > create space **and** Change someone’s cell > Move someone temporarily out of a cell
- shows 'Select another cell' content on back link when going through the route change cell > single occupancy/multiple occupancy 
- ‘Select another cell’ link now takes the user to 'select another cell' page
=> Nn 3035 variable cancel link

backend/controllers/prisonerProfile/prisonerWorkAndSkills.ts, backend/tests/prisonerWorkAndSkills.test.ts
This PR:
- adds a check on the ESWE_ENABLED feature flag, which if false, redirects the user back to the prisoner profile if they go to `/work-and-skills`
- adds a couple of tests for the work and skills controller, one to test the feature flag and one to test the render
=> Nn 3566 add page feature flag

backend/api/curious/curiousApi.ts, backend/api/curious/types/index.d.ts, backend/controllers/prisonerProfile/prisonerWorkAndSkills.ts, backend/services/esweService.ts, backend/tests/esweService.test.ts, backend/tests/prisonerWorkAndSkills.test.ts, integration-tests/integration/prisonerProfile/prisonerWorkAndSkills.spec.js, integration-tests/mockApis/curiousApi.js, integration-tests/plugins/index.js, views/prisonerProfile/prisonerWorkAndSkills/partials/prisonerGoals.njk, views/prisonerProfile/prisonerWorkAndSkills/prisonerWorkAndSkills.njk
This PR introduces the goals accordion within the work and skills tab.
Goals set example:
No goals set example:
user not in curious 404 example:
API error example:
=> ESWE-46-add goals accordion

backend/services/prisonerFinanceService.ts, backend/tests/prisonerFinanceService.test.ts
Otherwise there is the risk that the object that holds it is not reinstated, thus causing old dates to be used
=> NN-3626: Always construct current date object on function calls

backend/controllers/attendance/houseblockList.ts, backend/tests/houseblockList.test.ts
When filtering on activities for staying, include IN_CELL activities
=> NN-3616: Add IN_CELL location code as staying-on-wing

backend/services/esweService.ts, backend/tests/esweService.test.ts, integration-tests/integration/prisonerProfile/prisonerWorkAndSkills.spec.js, integration-tests/plugins/index.js
This PR:
- adds an extra filter to the getCurrentWork function within the ESWE service in order to show only jobs that are in the current caseload
Also: applies the stringWithAbbreviationsProcessor function to an uppercase establishment name
=> ESWE-47 add extra filter to current work

backend/controllers/downloadProbationDocument.ts, backend/controllers/probationDocuments.ts, backend/routes.ts, backend/services/prisonerProfileService.ts, backend/shared/probationDocumentsAccess.ts, backend/tests/downloadProbationDocument.test.ts, backend/tests/prisonerProfileService.test.ts, backend/tests/probationDocuments.test.ts, integration-tests/integration/prisonerProfile/prisonerQuickLook.spec.js
To view probation document you now need to following
1) The correct role - this is unchanged
2) A caseload that matches the prisoner location - this is new
Therefore a POM can no longer view prisoners that have been released or in a another prisoner they don't have a caseload for.
This is a requested change from the MPC team alongside App Support
=> Dt 2880 probation documents protected by caseload

backend/config.ts, backend/services/prisonerProfileService.ts, backend/tests/prisonerProfileService.test.ts, helm_deploy/digital-prison-services/templates/_envs.tpl, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, views/prisonerProfile/partials/prisonerProfileHeader.njk
Adding a calculate release dates button to the prisoner profile page.
We're in the middle of creating our pre prod environment now. There is a sub task to check the url in the dps helm config when we have the service running, we will do the same thing with production
The button won't appear on preprod or prod because no one has the calc role currently. We will use the role to act as a feature toggle.
=> CRS-534 adding calculate release dates button to prisoner profile page.

backend/controllers/appointments/addAppointment.ts, backend/routes/appointments/addAppointmentRouter.ts, backend/tests/addAppointment.test.ts
Currently, the list shown for available locations for an appointment is a list from the USER'S caseload. It needs to be a list of locations at the PRISONER'S caseload. I've swapped the user's agency id for the prisoner's. I've also sorted the typescript errors in the files involved.
=> NN-3302: Fix add-appointment location list bug

backend/controllers/homepage/homepage.ts
Removed reference to 'review dates' as we're removing the 'Days since
last review'/'Days on level' columns in 'Manage incentives'.
=> INC-390: Copy change to 'Manage incentives' tile

Dockerfile
..otherwise it does not perform the apt-get upgrade, resulting in security failures
=> NN-4056: Add cache buster to docker file

backend/controllers/homepage/homepage.ts
Copy update to reflect the fact all users can now see the analytics section
with data visualisations.
=> INC-438: Manage incentives tile mentions 'Data visualisations'

backend/index.ts, backend/routes.ts
Reverts ministryofjustice/digital-prison-services#2162
=> NN-4019: Re-instate catch wrapper for probation docs

backend/config.ts, backend/controllers/homepage/homepage.ts, backend/tests/homepageController.test.ts, helm_deploy/digital-prison-services/templates/_envs.tpl, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
The legacy PVB is being re-animated for a short period of time whilst
its replacement is completed.  Previously PVB was only ever accessed via
its own service URL and therefore has never been used with DPS.
This PR adds a tile specifically for the legacy service so that we can
encourage users to access it via the preferred method.
Should resolve https://dsdmoj.atlassian.net/browse/VB-879
=> Add a new DPS tile for the Legacy PVB

backend/api/prisonApi.ts, backend/api/whereaboutsApi.ts, backend/controllers/attendance/offenderActivities.ts, backend/tests/offenderActivities.test.ts, integration-tests/integration/prisonersUnaccountedFor.spec.js, integration-tests/mockApis/prisonApi.js, integration-tests/mockApis/whereabouts.js, integration-tests/plugins/index.js
It still won't be speedy since there are issues with the Prison API endpoint.  Should be a bit better though as only making one call to get the data and also new 30 second timeout on the endpoint.
=> SDI-213: ♻️  Switch to new prisoners unaccounted for endpoint

backend/api/offenderSearchApi.test.ts, backend/api/offenderSearchApi.ts, backend/api/prisonApi.ts, backend/contextProperties.ts, backend/controllers/search/prisonerSearch.ts, backend/middleware/currentUser.ts, backend/routes.ts, backend/routes/prisonerSearchRouter.ts, backend/tests/contextProperties.test.ts, backend/tests/prisonerSearch.test.ts, cypress.config.js, docker-compose-test.yaml, integration-tests/integration/search/prisonerSearch.cy.js, integration-tests/mockApis/offenderSearch.js
1. Adds integration to `prisoner-offender-search` for the main DPS (establishment) search
2. Existing `prison-api` search is used by default
3. `prisoner-offender-search` can be used by adding `feature=new` to any /prisoner-search url
4. Old behaviour is replicated
=> SDI-311 Elastic search for establishment search

backend/api/incentivesApi.ts, backend/api/oauthEnabledClient.ts, backend/controllers/prisonerProfile/prisonerChangeIncentiveLevelDetails.ts, backend/controllers/prisonerProfile/prisonerIncentiveLevelDetails.ts, backend/controllers/prisonerProfile/prisonerQuickLook.ts, backend/controllers/search/prisonerSearch.ts, backend/tests/movementsService.test.ts, backend/tests/prisonerChangeIncentiveLevelDetails.test.ts, backend/tests/prisonerIncentiveLevelDetails.test.ts, backend/tests/prisonerProfileService.test.ts, backend/tests/prisonerQuickLook.test.ts, backend/utils.ts, integration-tests/integration/prisonerProfile/prisonerChangeIncentiveLevelDetails.cy.js, integration-tests/integration/prisonerProfile/prisonerIncentiveLevelDetails.cy.js
• Adds parameter and return types to incentives api object 
• Fixes some types in OAuth client api (e.g. POST methods _do_ in fact expect a body param)
• Fixes test mocks (a few used incorrect types, but test _logic_ all remains unchanged)
• Only functional code change is: IEP summary details aren't loaded on the incentive recording page (because they're unused)
=> INC-814: Improve incentives api types

backend/api/prisonApi.ts, backend/controllers/prisonerProfile/prisonerIncentiveLevelDetails.ts, backend/tests/prisonerIncentiveLevelDetails.test.ts, integration-tests/integration/prisonerProfile/prisonerIncentiveLevelDetails.cy.js
For unmatched records we now visually get "not entered" which we can iterate on by stops the screen crashing
=> INC-860 Fix DPS incentive level details page when history includes system generated reviews

backend/shared/alertFlagValues.ts, backend/tests/establishmentRoll/inReceptionController.test.ts, backend/tests/prisonerSearch.test.ts, sass/components/_alert-flags.scss
**Add VISOR alert to the list of DPS alerts**
Acceptance Criteria
• Unsaved changes
The alert should be visible in the 
Global Prisoner Search – for example [HMPPS Digital Services - Sign in](https://digital-dev.prison.service.justice.gov.uk/prisoner-search?keywords=&location=MDI)
Prisoner Profile –  for example [HMPPS Digital Services - Sign in](https://digital-dev.prison.service.justice.gov.uk/prisoner/G6123VU) 
ViSOR Nominal (PVN) is an existing alert that can be added to a prisoner profile. The type of alert is ‘MAPPP Case' and the alert is called 'ViSOR nominal’.
The alert label will appear with the other labels at the top of the Prisoner profile, when the alert has been added to a prisoner’s record.
The label should read ViSOR in capital letters (lower case i) and be #003078 …
=> NN-4481: alerts add visor

backend/controllers/search/prisonerSearch.ts, backend/tests/prisonerSearch.test.ts
…because it's started to enforce validation (submitted booking ids cannot be an empty list)
=> Stop calling incentives-api when prisoner search finds no results

backend/controllers/globalSearch.ts
**Bug**
Backlink that is stored in the session in the local establishment search isn't cleared out when searching using global search. 
**Solution**
Clear the saved backlink when using global search.
=> NN-4458 clear backlink from session

backend/config.ts, backend/controllers/caseNote.ts, backend/routes/caseNoteCreationRouter.ts, backend/tests/caseNote.test.ts, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, sass/application.scss, views/caseNotes/recordIncentiveLevelInterruption.njk
…so that users know they must also record an incentive level review in another part of DPS. Amending a case note does not require this reminder.
This will be conditionally enabled for a few prisons for private beta rollout. For now, it’s on in `dev` and `preprod` for Leeds and Moorland.
=> INC-945: Interrupt flow when adding Incentive Level Review case note

backend/controllers/search/prisonerSearch.ts, backend/tests/prisonerSearch.test.ts
This ensures search for block `C` doesn't bring back prisoner in block `Cswap`
=> SDI-509 House block appended with `dash`

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
See also: [hmpps-incentives-ui#356](https://github.com/ministryofjustice/hmpps-incentives-ui/pull/356)
Should be deployed on 4 Jan.
=> INC-953: Enable case note entry interruption for private beta technical check of ‘Manage Incentives’

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
See also: [hmpps-incentives-ui#354](https://github.com/ministryofjustice/hmpps-incentives-ui/pull/354)
Should be deployed on 5 Jan.
=> INC-953: Enable case note entry interruption for private beta prison groups 1 & 2 of ‘Manage Incentives’

.circleci/config.yml
Pin npm to 9.2.0 because of the issue https://github.com/npm/cli/issues/6051 
See Slack thread https://mojdt.slack.com/archives/C69NWE339/p1673607422599409
=> Pin CircleCI npm to 9.2.0

helm_deploy/values-dev.yaml
The datacompliance API is broken in dev - not sure why, think it's related to secret rotation - but for now we need to turn off datacompliance requests from DPS to get DPS working again.
=> SDI-592 Turn off datacompliance in dev

helm_deploy/values-dev.yaml, integration-tests/integration/prisonerProfile/prisonerPersonal.cy.js, views/prisonerProfile/prisonerPersonal/partials/neurodiversities.njk
Add Moorland to the list of sites allowed to view neurodiversity data.
Update message displayed when no neurodiversity data found.
Reviewers
@natclamp-moj
=> ESWE-420_neurodiversity_enable_moorland

views/prisonerProfile/prisonerIncentiveLevelDetails.njk
This date is currently not accurate. This is the date of the last Incentive record which is not necessarily an Incentive review (it could be a transfer for example).
=> INC-1103: Removed 'Date of last review' from Incentive details page

helm_deploy/values-prod.yaml
**NOTE**: This can be merged/deployed on Monday.
This is the list of new private beta prisons:
| ID  | Prison name     |
|-----|-----------------|
| BFI | Bedford         |
| BLI | Bristol         |
| BRI | Bure            |
| CDI | Chelmsford      |
| HBI | Hollesley Bay   |
| HPI | Highpoint       |
| HVI | Haverigg        |
| KMI | Kirkham         |
| LCI | Leicester       |
| LFI | Lancaster Farms |
| LII | Lincoln         |
| LTI | Littlehey       |
| LYI | Leyhill         |
| MHI | Morton Hall     |
| MTI | The Mount       |
| NSI | North Sea Camp  |
| NWI | Norwich         |
| ONI | Onley           |
| PDI | Portland        |
| PNI | Preston         |
| VEI | The Verne       |
| WLI | Wayland         |
| WMI | Wymott          |
| WTI | Whatton         |
=> INC-1151: March 20th: More prisons to private beta

backend/config.ts, backend/controllers/homepage/homepage.ts, backend/tests/homepageController.test.ts, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, integration-tests/integration/homepage/homepage.cy.js
The tile shows for:
• regular users in a prison – would have at least one "location" _irrespective_ of their roles
• central admins – won’t have locations but will have `MAINTAIN_INCENTIVE_LEVELS` role
LSAs would need to use their normal account. An LSA’s special account would have the active case load of `CADM_I` but no locations.
NB: first commit is just to rearrange test cases; the tests themselves are unchanged
=> INC-1238: Show Manage incentives tile to appropriate user groups

backend/controllers/prisonerProfile/prisonerProfileBackLinkRedirect.ts, backend/controllers/prisonerProfile/prisonerProfileRedirect.ts, backend/middleware/currentUser.test.ts, backend/middleware/currentUser.ts, backend/routes.ts, backend/routes/prisonerProfileRouter.ts
Added conditional redirect for `save-backlink` route to use prisoner profile save-backlink
Removed oauth call to get roles - got roles from token and added `userRoles` to `res.locals.user` instead
Needs to be merged alongside PR for `hmpps-prisoner-profile` - https://github.com/ministryofjustice/hmpps-prisoner-profile/pull/143
=> CDPS-159: Prisoner profile back links

backend/controllers/homepage/homepage.ts, backend/routes.ts
- Redirects all appointments routes to new service if appointments is rolled out for that prison
- Redirects the add appointment route linked to from the prisoner profile to the start of the new create individual appointment journey
- Adds "View prisoners unaccounted for" tile from Whereabouts submenu
=> SAA-806 & SAA-825: Redirect all appointment routes to new service when rolled out

backend/routes.ts
Changes the individual appointment specific /appointments/create/start-individual?prisonNumber=A1234BC link for the prisoner profile to the more journey agnostic /appointments/create/start-prisoner/A1234BC link
=> SAA-967: Change add appointment redirect to appointment type agnostic link

helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
We are ready to deploy this to production now so the feature flag can be disabled. We can completely remove the feature flag code soon, once we are sure we won't need to roll back.
=> MAP-36: Disable non-associations legacy mode for preprod and prod

backend/api/nonAssociationsApi.ts, backend/controllers/cellMove/cellMoveUtils.ts, backend/controllers/cellMove/searchForCell.ts, backend/controllers/cellMove/selectCell.ts, backend/controllers/cellMove/viewNonAssociations.ts, backend/tests/cellMove/cellMoveUtils.test.ts, integration-tests/integration/cellMove/searchForCell.cy.js, integration-tests/integration/cellMove/selectCell.cy.js
Previously we were filtering non-associations based on the location from the non-association record. This creates problems if the non-association was created against a previous booking, as the last location will be `OUTSIDE`. Now we check the current location of each prisoner and compare them instead.
=> MAP-158: Filter non-associations based on current location

backend/controllers/cellMove/cellMoveUtils.ts, backend/tests/cellMove/cellMoveUtils.test.ts, backend/tests/cellMove/searchForCell.test.ts, backend/tests/cellMove/selectCell.test.ts, backend/tests/cellMove/viewNonAssociations.test.ts, integration-tests/integration/cellMove/searchForCell.cy.js, integration-tests/integration/cellMove/selectCell.cy.js, integration-tests/integration/cellMove/viewNonAssociations.cy.js, integration-tests/mockApis/prisonApi.js
Non-associations from past bookings were not displaying the living unit description when the summary was viewed
=> MAP-158: Display correct cell location when displaying non-associations

backend/controllers/getConfig.ts, backend/controllers/homepage/homepage.ts, src/App.js
When activities is rolled out for a prison:
- The "View prisoners unaccounted for" tile will no longer be shown on the DPS homepage or Whereabouts sub menu
- The /manage-prisoner-whereabouts/prisoners-unaccounted-for route for the "View prisoners unaccounted for" will redirect to the DPS homepage in line with the other replaced Whereabouts routes
=> SAA-1018: Remove unused activities tile. Redirect when activities rolled out

backend/controllers/cellMove/cellMoveUtils.ts, backend/tests/cellMove/cellMoveUtils.test.ts
We recently updated the cell moves code to pull the details of each non-association via the prison API. This uses the currently logged-in user's creds, and they may not have permissions to view users in other establishments. This was causing errors when requesting cell moves for some prisoners. The fix is to ignore the failed lookups as we only care about prisoners in the same establishment anyway.
=> MAP-202: Fix cell moves bug with non-associations in other establishments

backend/controllers/cellMove/considerRisks.ts, backend/controllers/cellMove/searchForCell.ts, backend/controllers/cellMove/selectCell.ts, backend/tests/cellMove/considerRisks.test.ts, backend/tests/cellMove/searchForCell.test.ts, backend/tests/cellMove/selectCell.test.ts, integration-tests/integration/cellMove/confirmCellMove.cy.js, integration-tests/integration/cellMove/considerRisks.cy.js, integration-tests/integration/cellMove/searchForCell.cy.js, integration-tests/integration/cellMove/selectCell.cy.js, views/cellMove/confirmCellMove.njk, views/cellMove/considerRisks.njk, views/cellMove/searchForCell.njk, views/cellMove/selectCell.njk
What?
- Change breadcrumbs to back links on cell moves main journey pages
Why?
- To conform with new DPS breadcrumb guidelines
Ticket
- https://dsdmoj.atlassian.net/browse/MAP-246
=> MAP-246: Change cell moves breadcrumbs to back buttons

views/cellMove/cellMoveHomepage.njk
the beginning of breadcrumb doesn't have chevron whereas back link does. Note: Breadcrumb now sits slightly higher but this is consistent with other pages/services
old
new
=> MAP-266 changed backlink to breadcrumb to remove chevron

helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
Enable non-association links from prisoner profile in the other 3 private beta prisons (FNI,LGI,RSI)
This PR follows: https://github.com/ministryofjustice/digital-prison-services/pull/2575
**NOTE**: This cannot be merged/released until we go live in these private beta prisons. We'll leave it as a draft PR for the time being.
=> NON-261: non-associations private beta - Part 2

backend/controllers/receptionMove/considerRisksReception.ts, backend/controllers/receptionMove/receptionFull.ts, backend/routes/receptionMoveRouter.ts, backend/tests/receptionMove/considerRisksReceptionController.test.ts, backend/tests/receptionMove/receptionFullController.test.ts, views/partials/layout.njk, views/receptionMoves/receptionFull.njk
user redirected to /reception-moves/reception-full if there is no room in reception when they try to get to /reception-move/consider-risks-reception
The backlink in /reception-moves/reception-full not displayed if the user navigate's to page by adding url to search bar directly.
=> Map 290 dps reception full page

backend/controllers/receptionMove/considerRisksReception.ts, backend/tests/receptionMove/considerRisksReceptionController.test.ts
corrected logic to display the reception-full page.
prisonApi.getReceptionsWithCapacity returns an empty array if there is no capacity so previous logic was attempting to destruct a null object
=> MAP-290 fix logic that determines reception capacity

backend/api/prisonApi.ts, integration-tests/integration/signIn/signIn.cy.js
A tweak to an earlier change allowing for errors from prison-api endpoint which checks what roles the current user has. This endpoint now enforces tighter restrictions so can reject calls from CADMs (who may not have a relevant caseload)
=> SDIT-1384 StaffResource - catch access error

backend/controllers/receptionMove/confirmReceptionMove.ts, backend/controllers/receptionMove/considerRisksReception.ts, backend/tests/receptionMove/confirmReceptionMoveController.test.ts, backend/tests/receptionMove/considerRisksReceptionController.test.ts
1. content change on reception-move/consider-risks-reception page. If only one prisoner in reception, should show ‘1 person in reception’. Otherwise should display   ‘ x people in reception’ 
2. when moving prisoner from cell to reception then back from reception to cell again, the app currently persists the radio selection button selected and the comments entered in the  confirmation pages. These should not be carried over. i.e cell-move/confirm-cell-move should not present any selections or comments that were set in /reception-move/confirm-reception-move
=> MAP-664 bugfix

backend/api/locationsInsidePrisonApi.test.ts, backend/api/locationsInsidePrisonApi.ts, backend/controllers/selectResidentialLocation.ts, backend/routes.ts, backend/tests/selectResidentialLocation.test.ts, cypress.config.js, integration-tests/integration/activity/houseblockList.cy.js, integration-tests/integration/whereabouts/selectResidentialLocation.cy.js, integration-tests/mockApis/locationsInsidePrisonApi.js
see Jira [MAP-1287](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?quickFilter=3684&selectedIssue=MAP-1287)
Replacing call to whereaboutsApi.searchGroups() with locationsInsidePrisonApi.getSearchGroups() for the selectResidentialLocation.ts module.
There are other module's that still rely on whereaboutsApi.searchGroups() so it has not been removed from the codebase yet. 
[MAP-1287]: https://dsdmoj.atlassian.net/browse/MAP-1287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MAP-1287 /select-residential-location to gets groups from locationsApi

backend/controllers/appointments/viewAppointments.ts, backend/tests/viewAppointmentsController.test.ts, integration-tests/integration/appointments/viewAppointments.cy.js
moving away from whereaboutsApi to locationsInsidePrisonApi to get internal location groups.
Change applied to viewAppointments.ts so that it gets location groups from locationsInsidePrisonApi
Page affected is /view-all-appointments and component is the Residential Location select box
=> MAP-1287 now getting residential location groups from locationsApi

backend/api/whereaboutsApi.ts, backend/controllers/attendance/houseblockLocations.ts, backend/setupApiRoutes.ts, backend/tests/houseBlockLocations.test.ts, backend/tests/viewAppointmentsController.test.ts, cypress.config.js, integration-tests/integration/activity/activityList.cy.js, integration-tests/integration/activity/houseblockList.cy.js, integration-tests/integration/activity/selectActivityLocation.cy.js, integration-tests/integration/whereabouts/selectResidentialLocation.cy.js, integration-tests/mockApis/whereabouts.js
Call to locationsApi replaces call previously made to whereaboutsApi
Removed any remaining references to whereaboutsApi.searchGroups()
Affects /manage-prisoner-whereabouts/housing-block-results
=> MAP-1287 use locationsApi to get house block groups for houseblockLocations

backend/api/caseNotesApi.test.ts, backend/api/caseNotesApi.ts, backend/controllers/caseNote.ts, backend/controllers/prisonerProfile/prisonerCaseNotes.ts, backend/tests/caseNote.test.ts, backend/tests/caseNotesController.test.ts, integration-tests/mockApis/caseNotes.js
this PR corresponds to the same changes in prisoner profile: https://github.com/ministryofjustice/hmpps-prisoner-profile/pull/706
- replace GET /case-notes/types-for-user call with GET /case-notes/types using the correct filters. GET /case-notes/type-for-user endpoint will be deprecated.
- set query params of what kind of CaseNoteSubTypes to be included for GET /case-notes/types calls (namely, selectable by DPS_USER or by ALL; include INACTIVE and/or RESTRICTED subtypes), based on the user's roles.
=> MICN-113 use filtered case note type and sub type endpoint

backend/controllers/caseNote.ts, backend/tests/caseNote.test.ts, integration-tests/mockApis/caseNotes.js
MICN-164
`activeFlag` is now only used for Case Note Child type but not on Parent type.
and it is refactored into a boolean (`active`) in offender-case-notes service.
This PR updates case note api service to follow the updated API specs of offender-case-notes
=> MICN-164 Update case note subtype to use `active` instead of `activeFlag`

helm_deploy/digital-prison-services/values.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
The BVLS team are preparing for rollout, and we have various feature toggles to flip on, on the day of rollout. To reduce dependency and disruption on other teams, we want to convert the toggles to namespace secrets, so that we can flip their value without the need for a new helm deployment.
The secret has been applied to the relevant Digital Prison Service namespaces:
- dev = true
- preprod = true
- prod = false.
=> BAVL-382 moving feature toggle to K8s so can switch toggle without having to redeploy the service.

backend/routes.ts, views/whereaboutsServiceDeactivated.njk
UI Redirect to prevent user actioning attendance in whereabouts service when activities and appointments service is live
=> SAA-2029: Whereabouts-UI-add-no-longer-in-service-page

backend/api/bookAVideoLinkApi.ts, backend/api/locationsInsidePrisonApi.ts, backend/api/nomisMappingClient.ts, backend/apis.ts, backend/config.ts, backend/index.ts, backend/routes.ts, backend/services/appointmentDetailsService.ts, backend/services/healthCheck.ts, backend/services/videoLinkBookingService.ts, backend/setupHealthChecks.ts, backend/tests/appointmentDetails.test.ts, backend/tests/appointmentDetailsService.test.ts, cypress.config.js, cypress.env, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, integration-tests/integration/health.cy.js, integration-tests/mockApis/nomisMapping.js
The whereabouts API works using NOMIS location ids.
The BVLS API works using LocationsAPI location ids.
Up until now, we have assumed that the locationPrefix of a nomis location is equal to the business key of the locations returned from Locations API. However, this assumption is not always the case, namely at HMP Thameside.
Nomis location ids (fetched from Whereabouts API) must be mapped to DPS location keys using the NomisMapping tool provided by Syscon, for use when communicating with BVLS API and vice versa
=> Map old Prison API locations to new Locations for Video Link Bookings

backend/controllers/appointments/viewAppointments.ts, backend/routes.ts, backend/services/appointmentDetailsService.ts, backend/tests/appointmentDetails.test.ts, backend/tests/appointmentDetailsService.test.ts, backend/tests/viewAppointmentsController.test.ts, integration-tests/integration/appointments/viewAppointments.cy.js
* Fix issue where bookings were being mismatched between Whereabouts and BVLS
* Fix issue where probation bookings would say `Added by: Court`
=> BAVL-572 & BAVL-573: Include location when mapping an appointment to a video link booking, and fix added by field for probation users

backend/services/appointmentDetailsService.ts, backend/tests/appointmentDetailsService.test.ts
Small content change for BLVS appointments to show 'None entered' instead of 'Not entered' for notes when none present for consistency across services.
=> BAVL-901 small content changes for the BVLS court and probation appointments containing notes.

backend/services/appointmentDetailsService.ts, backend/tests/appointmentDetailsService.test.ts
Small adjustment to the labels for BVLS appointment types on the appointment details screen.
=> BAVL-901 BVLS label changes for notes for VLB and VLPM appointment types.
